/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_DataValue2.h"

@interface PBXGDB_DescriptionDataValue : PBXGDB_DataValue2
{
}

- (void)requestReleaseChildren;
- (void)release;
- (id)retain;
- (id)initWithDebugger:(id)arg1;

@end

