/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_BaseDataValueSequence.h"

@class NSMutableArray;

@interface PBXGDB_ArrayDataValueSequence : PBXGDB_BaseDataValueSequence
{
    unsigned long long _childIndex;
    NSMutableArray *_addedChildren;
}

+ (id)sequenceWithContainerDV:(id)arg1 dataValue:(id)arg2;
- (void)didFinish;
- (void)_gotSTLContainerArrayElement:(id)arg1;
- (void)_gotSTLContainerDVSizeValue:(id)arg1;
- (void)_fetchElementsInRange:(struct _NSRange)arg1;
- (void)_gotSTLContainerDVSizeVarObj:(id)arg1;
- (void)execute;
- (id)containerExpressionForIndex:(long long)arg1;
- (id)sizeExpression;
- (BOOL)handleErrorForMICommand:(id)arg1;
- (double)timeOutPeriod;
- (void)dealloc;
- (id)init;

@end

