/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_MICommand.h"

@class NSString;

@interface PBXGDB_MIUserCommand : PBXGDB_MICommand
{
    NSString *_userCommandString;
    long long _selectedFrameIndex;
    long long _selectedThreadIndex;
    BOOL _shouldFetchStack;
}

- (BOOL)shouldFetchStack;
- (long long)selectedThreadIndex;
- (long long)selectedFrameIndex;
- (void)didFinishWithResultList:(id)arg1;
- (id)GDBCommandString;
- (id)rawCommandString;
- (void)setUserCommandString:(id)arg1;
- (void)willExecute;
- (void)dealloc;
- (id)initWithSequenceNumber:(unsigned long long)arg1;

@end

