/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_WCharStringFetchOperation.h"

@interface PBXGDB_WCharCharacterFetchOperation : PBXGDB_WCharStringFetchOperation
{
}

- (void)perform;
- (Class)stringFetchSequenceClass;
- (unsigned long long)charactersToRead;
- (unsigned long long)defaultEncoding;

@end

