/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_MISingleVarObjCommand.h"

@class NSString;

@interface PBXGDB_MIGetValueVarObjCommand : PBXGDB_MISingleVarObjCommand
{
    NSString *_valueString;
}

- (id)valueString;
- (void)didFinishWithResultList:(id)arg1;
- (void)setVarObjName:(id)arg1;
- (void)dealloc;

@end

