/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_BaseDataValueSequence.h"

@interface PBXGDB_DeleteDataValueChildrenSequence : PBXGDB_BaseDataValueSequence
{
    BOOL _freeVarObjs;
}

- (void)execute;
- (BOOL)freeVarObjs;
- (void)setFreeVarObjs:(BOOL)arg1;
- (void)_gotDeletedChildrenOfVarObj:(id)arg1;

@end

