/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_MICommand.h"

@class NSString;

@interface PBXGDB_MIMovePC : PBXGDB_MICommand
{
    unsigned long long _threadID;
    NSString *_fileAndLine;
}

- (void)didFinishWithResultList:(id)arg1;
- (id)GDBCommandString;
- (id)fileAndLine;
- (void)setFileAndLine:(id)arg1;
- (void)setThreadID:(unsigned long long)arg1;
- (unsigned long long)threadID;
- (void)dealloc;

@end

