/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface PBXGDB_MIResultList : NSObject
{
    NSMutableArray *_items;
    NSMutableDictionary *_itemsDict;
    NSString *_name;
}

+ (id)padStringForLevel:(unsigned long long)arg1;
- (id)name;
- (void)setName:(id)arg1;
- (id)itemWithKey:(id)arg1;
- (void)removeAllItems;
- (id)items;
- (void)addItem:(id)arg1;
- (id)description;
- (id)descriptionAtLevel:(unsigned long long)arg1;
- (void)dealloc;
- (id)init;

@end

