/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_Controller.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet;

@interface PBXGDB_BreakpointController : PBXGDB_Controller
{
    NSMutableSet *_breakpointSet;
    unsigned long long _pendingBreakpointCount;
    NSMutableDictionary *_watchpointDict;
    NSMutableArray *_cppExceptionThrows;
    NSMutableArray *_cppExceptionCatches;
}

+ (id)_createRegexForBreakpoints:(id)arg1;
- (void)enqueueNewWatchpointSequenceForDataValue:(id)arg1;
- (void)enqueueDeleteWatchpointSequenceForDataValue:(id)arg1;
- (long long)watchpointNumberForDataValue:(id)arg1;
- (id)dataValueForWatchpointNumber:(long long)arg1;
- (void)setDataValue:(id)arg1 forWatchpointNumber:(long long)arg2;
- (void)breakpointConditionCommandChanged:(id)arg1;
- (id)gdbCommandStringForBreakpoint:(id)arg1;
- (void)breakpointIgnoreCountChanged:(id)arg1;
- (void)resetExceptionBreakpointData;
- (void)rescanBreakpoints;
- (unsigned long long)pendingBreakpointCount;
- (void)resolvedAllMatchesOfBreakpointInfo:(id)arg1;
- (id)cppBreakpointWithExceptionName:(id)arg1 onThrow:(BOOL)arg2;
- (void)enqueueStopOnCPPCatchSequence;
- (void)enqueueDeleteStopOnCPPCatchSequence;
- (void)enqueueStopOnCPPThrowSequence;
- (void)enqueueDeleteStopOnCPPThrowSequence;
- (void)enqueueSetEnableBreakpointSequenceForPBXBreakpoint:(id)arg1;
- (void)enqueueTurnBreakpointOnOffSequence:(BOOL)arg1;
- (void)_enqueueSetEnableBreakpointSequenceForBreakpointInfo:(id)arg1;
- (void)enqueueDeleteBreakpointSequenceForPBXBreakpoint:(id)arg1;
- (void)_enqueueDeleteBreakpointSequenceForBreakpointInfo:(id)arg1;
- (BOOL)_findDynamicLinkerImageForBreakpointInfo:(id)arg1;
- (void)enqueueNewBreakpointSequenceForPBXBreakpoint:(id)arg1;
- (void)setConditionAndCommandForBreakpoint:(id)arg1 gdbNumber:(long long)arg2;
- (id)pathsOfProductsThatIncludeBreakpoint:(id)arg1;
- (id)productPathForBreakpoint:(id)arg1 inTarget:(id)arg2 currentExecutable:(id)arg3;
- (void)setGDBNumber:(long long)arg1 forBreakpoint:(id)arg2;
- (void)_enqueueNewBreakpointSequenceForBreakpointInfo:(id)arg1;
- (void)enqueBreakpointCommandSequence:(id)arg1 forBreakpointNum:(long long)arg2;
- (void)enqueBreakpointIgnoreCountSequence:(long long)arg1 forBreakpointNum:(long long)arg2;
- (void)enqueBreakpointConditionSequence:(id)arg1 forBreakpointNum:(long long)arg2;
- (void)_initSequence:(id)arg1 breakpointInfo:(id)arg2;
- (id)_imageController;
- (id)_targetSetController;
- (void)deleteInfo:(id)arg1;
- (void)setConditionIsValid:(BOOL)arg1 forBreakpointNumber:(long long)arg2;
- (id)breakpointForGDBBreakpointNumber:(long long)arg1;
- (id)infoForPBXBreakpoint:(id)arg1;
- (void)dealloc;
- (id)init;

@end

