/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_StringFetchOperation.h"

@interface PBXGDB_UnicharStringFetchOperation : PBXGDB_StringFetchOperation
{
}

- (Class)fetchResultSequenceClass;
- (Class)stringFetchSequenceClass;
- (unsigned long long)defaultEncoding;
- (unsigned long long)bytesPerCharacter;

@end

