/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_StringFetchResult.h"

@interface PBXGDB_UnicharFetchResult : PBXGDB_StringFetchResult
{
}

- (void)processStringData;
- (void)makeRepresentationOfNSString:(id)arg1 stopAtNull:(BOOL)arg2 stopAtDoubleNull:(BOOL)arg3 resultString:(id)arg4;

@end

