/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_MICommand.h"

@class NSArray, NSString;

@interface PBXGDB_MIBaseBreakpointCommand : PBXGDB_MICommand
{
    unsigned long long _contextNumber;
    long long _breakpointNumber;
    NSString *_addressString;
    NSString *_shlib;
    long long _bkptIndex;
    NSArray *_bkptItemArray;
}

- (void)didFinishWithResultList:(id)arg1;
- (void)setBreakpointItemArray:(id)arg1;
- (id)nextBreakpointItem;
- (id)shlib;
- (void)setShlib:(id)arg1;
- (id)addressString;
- (void)setAddressString:(id)arg1;
- (long long)gdbBreakpointNumber;
- (void)setGDBBreakpointNumber:(long long)arg1;
- (unsigned long long)contextNumber;
- (void)setContextNumber:(unsigned long long)arg1;
- (void)dealloc;

@end

