/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_BaseSharedLibrarySequence.h"

@interface PBXGDB_InferiorAutoStartDyldSequence : PBXGDB_BaseSharedLibrarySequence
{
    BOOL _enabled;
}

- (void)execute;
- (void)_done:(id)arg1;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)interruptIfNeeded;

@end

