/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_BaseThreadSequence.h"

@interface PBXGDB_StepControlSequence : PBXGDB_BaseThreadSequence
{
    int _stepSequenceType;
    unsigned long long _untilLineNumber;
}

- (void)execute;
- (void)_resultAllThreadsStepping:(id)arg1;
- (unsigned long long)untilLineNumber;
- (void)setStepUntilLineNumber:(unsigned long long)arg1;
- (int)stepSequenceType;
- (void)setStepSequenceType:(int)arg1;

@end

