/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_MISetSharedLibraryBaseCommand.h"

@class NSMutableString;

@interface PBXGDB_MISetSharedLibraryLoadSymbolsCommand : PBXGDB_MISetSharedLibraryBaseCommand
{
    NSMutableString *_rulesString;
}

+ (id)allNamesRegEx;
+ (id)executableLoadReason;
+ (id)cfmDynamicLinkerLoadReason;
+ (id)dyldDynamicLinkerLoadReason;
- (id)GDBCommandString;
- (void)addLoadRuleForReason:(id)arg1 nameRegEx:(id)arg2 symbolsLevel:(int)arg3;
- (id)_rulesString;
- (void)dealloc;

@end

