/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_MICommand.h"

@class NSString;

@interface PBXGDB_MIEvaluateExpressionCommand : PBXGDB_MICommand
{
    NSString *_stringValue;
}

- (BOOL)needsUnwindOnSignal;
- (id)stringValue;
- (void)setStringValue:(id)arg1;
- (void)setExpression:(id)arg1;
- (void)didFinishWithResultList:(id)arg1;
- (void)dealloc;

@end

