/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet, NSString, PBXTarget;

@interface PBXGDB_TargetSet : NSObject
{
    PBXTarget *_target;
    NSMutableSet *_components;
    BOOL _isFlat;
    BOOL _flattening;
    NSString *_targetPath;
}

- (id)targetProductResolvedAbsolutePath;
- (BOOL)containsFileReference:(id)arg1;
- (void)flattenComponentTargetSets;
- (id)targetSet;
- (void)_flattenComponentTargetSets;
- (id)target;
- (void)setTarget:(id)arg1;
- (void)addComponentTargetSet:(id)arg1;
- (void)removeComponentTarget:(id)arg1;
- (void)addComponentTarget:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithTarget:(id)arg1;
- (id)init;

@end

