/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_BaseBreakpointSequence.h"

@interface PBXGDB_DeleteBreakpointSequence : PBXGDB_BaseBreakpointSequence
{
}

- (void)execute;
- (void)_breakpointWasDeleted:(id)arg1;
- (void)_removeInfo;

@end

