/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_MIBaseBreakpointCommand.h"

@interface PBXGDB_MICreateFileBreakpointCommand : PBXGDB_MIBaseBreakpointCommand
{
}

- (void)setFileName:(id)arg1 lineNumber:(unsigned long long)arg2 futureBreak:(BOOL)arg3 resolveMultipleMatches:(BOOL)arg4 temporary:(BOOL)arg5 shlib:(id)arg6;

@end

