/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_CommandSequence.h"

@class PBXBreakpoint;

@interface PBXGDB_BreakpointActionEvaluateExpressionSequence : PBXGDB_CommandSequence
{
    PBXBreakpoint *_breakpoint;
    id _lastCmd;
}

+ (id)sequenceWithBreakpoint:(id)arg1;
- (BOOL)handleErrorForMICommand:(id)arg1;
- (void)breakpointActionExpressionEvaluated:(id)arg1;
- (void)execute;
- (void)dealloc;

@end

