/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface PBXGDB_MemoryRegion : NSObject
{
    unsigned long long remoteOrigin;
    unsigned long long localOrigin;
    unsigned long long mappedLength;
}

- (unsigned long long)localAddressForRemoteAddress:(unsigned long long)arg1;
- (BOOL)containsRemoteBuffer:(unsigned long long)arg1 length:(unsigned long long)arg2;
- (BOOL)containsRemoteAddress:(unsigned long long)arg1;
- (unsigned long long)mappedLength;
- (unsigned long long)remoteOrigin;
- (unsigned long long)localOrigin;
- (void)finalize;
- (void)dealloc;
- (id)initWithRemoteAddress:(unsigned long long)arg1 length:(unsigned long long)arg2 inTask:(unsigned int)arg3;

@end

