/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_CommandSequence.h"

@class PBXGDB_BreakpointController, PBXGDB_BreakpointInfo;

@interface PBXGDB_BaseBreakpointSequence : PBXGDB_CommandSequence
{
    PBXGDB_BreakpointController *_breakpointController;
    PBXGDB_BreakpointInfo *_breakpointInfo;
    long long _numCommands;
}

- (BOOL)interruptIfNeeded;
- (void)didFinish;
- (id)breakpointInfo;
- (void)setBreakpointInfo:(id)arg1;
- (id)breakpointController;
- (void)setBreakpointController:(id)arg1;
- (void)dealloc;

@end

