/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_CommandSequence.h"

@class XCUnretainedReference;

@interface PBXGDB_EvaluationSequence : PBXGDB_CommandSequence
{
    XCUnretainedReference *_operationRef;
}

- (BOOL)canExecuteCodeInTargetOnMyThread;
- (void)didFinish;
- (id)operation;
- (void)setOperation:(id)arg1;
- (void)dealloc;

@end

