/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXGDB_BaseDataValueSequence.h"

@class PBXGDB_DescriptionDataValue;

@interface PBXGDB_RegisterDataValueSetupSequence : PBXGDB_BaseDataValueSequence
{
    PBXGDB_DescriptionDataValue *_parentDV;
    long long _cmdCount;
}

+ (id)sequenceWithParentDV:(id)arg1 sequenceController:(id)arg2;
+ (id)sequenceToSetupCPUTypeWithSequenceController:(id)arg1;
- (void)execute;
- (void)setParentDV:(id)arg1;
- (void)didFinish;
- (void)gotCreatedRegisterVarObj:(id)arg1;
- (void)fetchRegistersForParentDV;
- (void)gotRegisterNames:(id)arg1;
- (void)dealloc;
- (double)timeOutPeriod;

@end

