/*  -*- buffer-read-only: t -*- vi: set ro:
 * 
 * DO NOT EDIT THIS FILE   (usage-txt.h)
 * 
 * It has been AutoGen-ed  January  9, 2014 at 07:32:08 PM by AutoGen 5.15
 * From the definitions    usage-txt.def
 * and the template file   usage-txt.tpl
 *
