---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"  # See docs for possible values
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "maven"
    directory: "/src/zlib/contrib/java/jzlib-1.1.2"
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      maven:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "nuget"
    directory: "/src/zlib/contrib/dotzlib/DotZLib"
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      nuget:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "gomod"
    directory: "/src/gdb/testsuite/gdb.go"
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      gomod:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "pip"
    directory: "/src/gdb"
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      pip:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "bundler"
    directory: "/src/gdb/ruby"
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      bundler:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      gradle:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/src/texinfo/js"
    schedule:
      interval: "weekly"
    labels:
      - enhancement
    groups:
      npm:
        patterns:
          - "*"
    cooldown:
      default-days: 7
