/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (opts.c)
 *  
 *  It has been AutoGen-ed  February 26, 2012 at 11:08:59 AM by AutoGen 5.15pre14
 *  From the definitions    opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 36:3:11 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the autogen author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The autogen program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 1992-2012 Bruce Korb, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  autogen is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  autogen is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#define OPTION_CODE_COMPILE 1
#include "opts.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (autogen_opt_strs+0)
#define zLicenseDescrip (autogen_opt_strs+273)

extern tUsageProc optionUsage;
/*
 *  global included definitions
 */

#include "autogen.h"
#ifdef HAVE_DLOPEN
# ifdef HAVE_DLFCN_H
#  include <dlfcn.h>
# else
   extern void* dlopen(char const*,int);
# endif

# ifndef  RTLD_GLOBAL
#  define RTLD_GLOBAL 0
# endif

# ifndef  RTLD_NOW
#  ifdef  RTLD_LAZY
#   define RTLD_NOW DL_LAZY
#  else
#   define RTLD_NOW 0
#  endif
# endif
#endif

#if HAVE_CTYPE_H
# include <ctype.h>
#else
# define isspace(_c)  0
#endif

typedef void (init_proc_t)(void);
char const * pzTemplFileName  = NULL;
ag_bool      trace_is_to_pipe = AG_FALSE;

#define CANNOT_LOCATE_FMT   (autogen_opt_strs+876)
#define LOAD_GUILE_FILE_FMT (autogen_opt_strs+908)

#define DLOPEN_ERROR_FMT    (autogen_opt_strs+920)
#define SYM_NOT_FOUND_FMT   (autogen_opt_strs+944)

#ifndef NULL
#  define NULL 0
#endif

/*
 *  autogen option static const strings
 */
static char const autogen_opt_strs[3265] =
/*     0 */ "autogen (GNU AutoGen) 5.15\n"
            "Copyright (C) 1992-2012 Bruce Korb, all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   273 */ "autogen is free software: you can redistribute it and/or modify it under\n"
            "the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "autogen is distributed in the hope that it will be useful, but WITHOUT\n"
            "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"
            "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License\n"
            "for more details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   876 */ "Cannot locate scheme file '%s'\n\0"
/*   908 */ "(load \"%s\")\0"
/*   920 */ "dlopen(%s) error %d\n"
            "%s\n\0"
/*   944 */ "dlsym(scm_init) not found in %s\n"
            "\tyou must initialize the library yourself\n\0"
/*  1019 */ "Template search directory list\0"
/*  1050 */ "TEMPL_DIRS\0"
/*  1061 */ "templ-dirs\0"
/*  1072 */ "Override template file\0"
/*  1095 */ "OVERRIDE_TPL\0"
/*  1108 */ "override-tpl\0"
/*  1121 */ "Library template file\0"
/*  1143 */ "LIB_TEMPLATE\0"
/*  1156 */ "lib-template\0"
/*  1169 */ "Base name for output file(s)\0"
/*  1198 */ "BASE_NAME\0"
/*  1208 */ "base-name\0"
/*  1218 */ "Definitions input file\0"
/*  1241 */ "DEFINITIONS\0"
/*  1253 */ "no-definitions\0"
/*  1268 */ "no\0"
/*  1271 */ "Scheme code file to load\0"
/*  1296 */ "LOAD_SCHEME\0"
/*  1308 */ "load-scheme\0"
/*  1320 */ "Load scheme function library\0"
/*  1349 */ "LOAD_FUNCTIONS\0"
/*  1364 */ "load-functions\0"
/*  1379 */ "Omit the file with this suffix\0"
/*  1410 */ "SKIP_SUFFIX\0"
/*  1422 */ "skip-suffix\0"
/*  1434 */ "specify this output suffix\0"
/*  1461 */ "SELECT_SUFFIX\0"
/*  1475 */ "select-suffix\0"
/*  1489 */ "set mod times to latest source\0"
/*  1520 */ "SOURCE_TIME\0"
/*  1532 */ "no-source-time\0"
/*  1547 */ "Do not use in-mem streams\0"
/*  1573 */ "NO_FMEMOPEN\0"
/*  1585 */ "no-fmemopen\0"
/*  1597 */ "characters considered equivalent\0"
/*  1630 */ "EQUATE\0"
/*  1637 */ "equate\0"
/*  1644 */ "_-^\0"
/*  1648 */ "Allow output files to be writable\0"
/*  1682 */ "WRITABLE\0"
/*  1691 */ "not-writable\0"
/*  1704 */ "not\0"
/*  1708 */ "The following options are often useful while debugging new templates:\0"
/*  1778 */ "Limit on increment loops\0"
/*  1803 */ "LOOP_LIMIT\0"
/*  1814 */ "loop-limit\0"
/*  1825 */ "name or path name of shell to use\0"
/*  1859 */ "SHELL\0"
/*  1865 */ "shell\0"
/*  1871 */ "Time limit for server shell\0"
/*  1899 */ "TIMEOUT\0"
/*  1907 */ "timeout\0"
/*  1915 */ "tracing level of detail\0"
/*  1939 */ "TRACE\0"
/*  1945 */ "trace\0"
/*  1951 */ "tracing output file or filter\0"
/*  1981 */ "TRACE_OUT\0"
/*  1991 */ "trace-out\0"
/*  2001 */ "Show the definition tree\0"
/*  2026 */ "SHOW_DEFS\0"
/*  2036 */ "show-defs\0"
/*  2046 */ "Show the definitions used\0"
/*  2072 */ "USED_DEFINES\0"
/*  2085 */ "used-defines\0"
/*  2098 */ "These options can be used to control what gets processed\n"
            "in the definitions files and template files.\0"
/*  2200 */ "name to add to definition list\0"
/*  2231 */ "DEFINE\0"
/*  2238 */ "define\0"
/*  2245 */ "definition list removal pattern\0"
/*  2277 */ "UNDEFINE\0"
/*  2286 */ "undefine\0"
/*  2295 */ "These options can be used to automate dependency tracking.\0"
/*  2354 */ "emit make dependency file\0"
/*  2380 */ "MAKE_DEP\0"
/*  2389 */ "make-dep\0"
/*  2398 */ "Leave a core dump on a failure exit\0"
/*  2434 */ "CORE\0"
/*  2439 */ "core\0"
/*  2444 */ "Display extended usage information and exit\0"
/*  2488 */ "help\0"
/*  2493 */ "Extended usage information passed thru pager\0"
/*  2538 */ "more-help\0"
/*  2548 */ "Output version information and exit\0"
/*  2584 */ "version\0"
/*  2592 */ "Reset an option's state\0"
/*  2616 */ "reset-option\0"
/*  2629 */ "Abbreviated usage to stdout\0"
/*  2657 */ "usage\0"
/*  2663 */ "Save the option state to a config file\0"
/*  2702 */ "save-opts\0"
/*  2712 */ "Load options from a config file\0"
/*  2744 */ "LOAD_OPTS\0"
/*  2754 */ "no-load-opts\0"
/*  2767 */ "AUTOGEN\0"
/*  2775 */ "autogen (GNU AutoGen) - The Automated Program Generator - Ver. 5.15\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [ <def-file> ]\n\0"
/*  2916 */ "$HOME\0"
/*  2922 */ ".\0"
/*  2924 */ ".autogenrc\0"
/*  2935 */ "autogen-users@lists.sourceforge.net\0"
/*  2971 */ "\n"
            "AutoGen creates text files from templates using external definitions.\n\0"
/*  3043 */ "\n"
            "AutoGen is a tool designed for generating program files that contain\n"
            "repetitive text with varied substitutions.\n\0"
/*  3157 */ "autogen (GNU AutoGen) 5.15\0"
/*  3184 */ "nothing\0"
/*  3192 */ "debug-message\0"
/*  3206 */ "server-shell\0"
/*  3219 */ "templates\0"
/*  3229 */ "block-macros\0"
/*  3242 */ "expressions\0"
/*  3254 */ "everything";

/*
 *  templ-dirs option description:
 */
/* TRANSLATORS: the option argument is a file name */
#define TEMPL_DIRS_DESC      (autogen_opt_strs+1019)
#define TEMPL_DIRS_NAME      (autogen_opt_strs+1050)
#define TEMPL_DIRS_name      (autogen_opt_strs+1061)
#define TEMPL_DIRS_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  override-tpl option description:
 */
#define OVERRIDE_TPL_DESC      (autogen_opt_strs+1072)
#define OVERRIDE_TPL_NAME      (autogen_opt_strs+1095)
#define OVERRIDE_TPL_name      (autogen_opt_strs+1108)
#define OVERRIDE_TPL_FLAGS     (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  lib-template option description:
 */
#define LIB_TEMPLATE_DESC      (autogen_opt_strs+1121)
#define LIB_TEMPLATE_NAME      (autogen_opt_strs+1143)
#define LIB_TEMPLATE_name      (autogen_opt_strs+1156)
#define LIB_TEMPLATE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  base-name option description:
 */
#define BASE_NAME_DESC      (autogen_opt_strs+1169)
#define BASE_NAME_NAME      (autogen_opt_strs+1198)
#define BASE_NAME_name      (autogen_opt_strs+1208)
#define BASE_NAME_FLAGS     (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  definitions option description:
 */
#define DEFINITIONS_DESC      (autogen_opt_strs+1218)
#define DEFINITIONS_NAME      (autogen_opt_strs+1241)
#define NOT_DEFINITIONS_name  (autogen_opt_strs+1253)
#define NOT_DEFINITIONS_PFX   (autogen_opt_strs+1268)
#define DEFINITIONS_name      (NOT_DEFINITIONS_name + 3)
#define DEFINITIONS_FLAGS     (OPTST_INITENABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  load-scheme option description:
 */
#define LOAD_SCHEME_DESC      (autogen_opt_strs+1271)
#define LOAD_SCHEME_NAME      (autogen_opt_strs+1296)
#define LOAD_SCHEME_name      (autogen_opt_strs+1308)
#define LOAD_SCHEME_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  load-functions option description:
 */
#ifdef HAVE_DLOPEN
#define LOAD_FUNCTIONS_DESC      (autogen_opt_strs+1320)
#define LOAD_FUNCTIONS_NAME      (autogen_opt_strs+1349)
#define LOAD_FUNCTIONS_name      (autogen_opt_strs+1364)
#define LOAD_FUNCTIONS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable load-functions */
#define LOAD_FUNCTIONS_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define LOAD_FUNCTIONS_NAME      NULL
#define LOAD_FUNCTIONS_DESC      NULL
#define LOAD_FUNCTIONS_name      NULL
#endif  /* HAVE_DLOPEN */

/*
 *  skip-suffix option description with
 *  "Must also have options" and "Incompatible options":
 */
#define SKIP_SUFFIX_DESC      (autogen_opt_strs+1379)
#define SKIP_SUFFIX_NAME      (autogen_opt_strs+1410)
#define SKIP_SUFFIX_name      (autogen_opt_strs+1422)
static int const aSkip_SuffixCantList[] = {
    INDEX_OPT_SELECT_SUFFIX, NO_EQUIVALENT };
#define SKIP_SUFFIX_FLAGS     (OPTST_DISABLED | OPTST_STACKED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  select-suffix option description:
 */
#define SELECT_SUFFIX_DESC      (autogen_opt_strs+1434)
#define SELECT_SUFFIX_NAME      (autogen_opt_strs+1461)
#define SELECT_SUFFIX_name      (autogen_opt_strs+1475)
#define SELECT_SUFFIX_FLAGS     (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  source-time option description:
 */
#define SOURCE_TIME_DESC      (autogen_opt_strs+1489)
#define SOURCE_TIME_NAME      (autogen_opt_strs+1520)
#define NOT_SOURCE_TIME_name  (autogen_opt_strs+1532)
#define NOT_SOURCE_TIME_PFX   (autogen_opt_strs+1268)
#define SOURCE_TIME_name      (NOT_SOURCE_TIME_name + 3)
#define SOURCE_TIME_FLAGS     (OPTST_DISABLED)

/*
 *  no-fmemopen option description:
 */
#define NO_FMEMOPEN_DESC      (autogen_opt_strs+1547)
#define NO_FMEMOPEN_NAME      (autogen_opt_strs+1573)
#define NO_FMEMOPEN_name      (autogen_opt_strs+1585)
#define NO_FMEMOPEN_FLAGS     (OPTST_DISABLED)

/*
 *  equate option description:
 */
#define EQUATE_DESC      (autogen_opt_strs+1597)
#define EQUATE_NAME      (autogen_opt_strs+1630)
#define EQUATE_name      (autogen_opt_strs+1637)
#define EQUATE_DFT_ARG   (autogen_opt_strs+1644)
#define EQUATE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  writable option description:
 */
#define WRITABLE_DESC      (autogen_opt_strs+1648)
#define WRITABLE_NAME      (autogen_opt_strs+1682)
#define NOT_WRITABLE_name  (autogen_opt_strs+1691)
#define NOT_WRITABLE_PFX   (autogen_opt_strs+1704)
#define WRITABLE_name      (NOT_WRITABLE_name + 4)
#define WRITABLE_FLAGS     (OPTST_DISABLED)

/*
 *  doc-debug option description:
 */
#define DOC_DEBUG_DESC      (autogen_opt_strs+1708)
#define DOC_DEBUG_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  loop-limit option description:
 */
#define LOOP_LIMIT_DESC      (autogen_opt_strs+1778)
#define LOOP_LIMIT_NAME      (autogen_opt_strs+1803)
#define LOOP_LIMIT_name      (autogen_opt_strs+1814)
#define LOOP_LIMIT_DFT_ARG   ((char const*)256)
#define LOOP_LIMIT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC) \
        | OPTST_SCALED_NUM)

/*
 *  shell option description:
 */
#ifdef SHELL_ENABLED
#define SHELL_DESC      (autogen_opt_strs+1825)
#define SHELL_NAME      (autogen_opt_strs+1859)
#define SHELL_name      (autogen_opt_strs+1865)
#define SHELL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable shell */
#define SHELL_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define SHELL_NAME      NULL
#define SHELL_DESC      NULL
#define SHELL_name      NULL
#endif  /* SHELL_ENABLED */

/*
 *  timeout option description:
 */
#ifdef SHELL_ENABLED
#define TIMEOUT_DESC      (autogen_opt_strs+1871)
#define TIMEOUT_NAME      (autogen_opt_strs+1899)
#define TIMEOUT_name      (autogen_opt_strs+1907)
#define TIMEOUT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

#else   /* disable timeout */
#define TIMEOUT_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define TIMEOUT_NAME      NULL
#define TIMEOUT_DESC      NULL
#define TIMEOUT_name      NULL
#endif  /* SHELL_ENABLED */

/*
 *  trace option description:
 */
#define TRACE_DESC      (autogen_opt_strs+1915)
#define TRACE_NAME      (autogen_opt_strs+1939)
#define TRACE_name      (autogen_opt_strs+1945)
#define TRACE_DFT_ARG   ((char const*)TRACE_NOTHING)
#define TRACE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_ENUMERATION))

/*
 *  trace-out option description:
 */
#define TRACE_OUT_DESC      (autogen_opt_strs+1951)
#define TRACE_OUT_NAME      (autogen_opt_strs+1981)
#define TRACE_OUT_name      (autogen_opt_strs+1991)
#define TRACE_OUT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  show-defs option description:
 */
#ifdef DEBUG_ENABLED
#define SHOW_DEFS_DESC      (autogen_opt_strs+2001)
#define SHOW_DEFS_NAME      (autogen_opt_strs+2026)
#define SHOW_DEFS_name      (autogen_opt_strs+2036)
#define SHOW_DEFS_FLAGS     (OPTST_DISABLED | OPTST_NO_INIT)

#else   /* disable show-defs */
#define SHOW_DEFS_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define SHOW_DEFS_NAME      NULL
#define SHOW_DEFS_DESC      (NULL)
#define SHOW_DEFS_name      (autogen_opt_strs+2036)
#endif  /* DEBUG_ENABLED */

/*
 *  used-defines option description:
 */
#define USED_DEFINES_DESC      (autogen_opt_strs+2046)
#define USED_DEFINES_NAME      (autogen_opt_strs+2072)
#define USED_DEFINES_name      (autogen_opt_strs+2085)
#define USED_DEFINES_FLAGS     (OPTST_DISABLED | OPTST_NO_INIT)

/*
 *  doc-control option description:
 */
#define DOC_CONTROL_DESC      (autogen_opt_strs+2098)
#define DOC_CONTROL_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  define option description:
 */
#define DEFINE_DESC      (autogen_opt_strs+2200)
#define DEFINE_NAME      (autogen_opt_strs+2231)
#define DEFINE_name      (autogen_opt_strs+2238)
#define DEFINE_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  undefine option description:
 */
#define UNDEFINE_DESC      (autogen_opt_strs+2245)
#define UNDEFINE_NAME      (autogen_opt_strs+2277)
#define UNDEFINE_name      (autogen_opt_strs+2286)
#define UNDEFINE_FLAGS     (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  doc-dependencies option description:
 */
#define DOC_DEPENDENCIES_DESC      (autogen_opt_strs+2295)
#define DOC_DEPENDENCIES_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  make-dep option description:
 */
#define MAKE_DEP_DESC      (autogen_opt_strs+2354)
#define MAKE_DEP_NAME      (autogen_opt_strs+2380)
#define MAKE_DEP_name      (autogen_opt_strs+2389)
#define MAKE_DEP_FLAGS     (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  core option description:
 */
#ifdef HAVE_SYS_RESOURCE_H
#define CORE_DESC      (autogen_opt_strs+2398)
#define CORE_NAME      (autogen_opt_strs+2434)
#define CORE_name      (autogen_opt_strs+2439)
#define CORE_FLAGS     (OPTST_DISABLED)

#else   /* disable core */
#define CORE_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define CORE_NAME      NULL
#define CORE_DESC      NULL
#define CORE_name      NULL
#endif  /* HAVE_SYS_RESOURCE_H */

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (autogen_opt_strs+2444)
#define HELP_name       (autogen_opt_strs+2488)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (autogen_opt_strs+2493)
#define MORE_HELP_name  (autogen_opt_strs+2538)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (autogen_opt_strs+2548)
#define VER_name        (autogen_opt_strs+2584)
#define RESET_DESC      (autogen_opt_strs+2592)
#define RESET_name      (autogen_opt_strs+2616)
#define RESET_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_NO_INIT)
#define USAGE_DESC      (autogen_opt_strs+2629)
#define USAGE_name      (autogen_opt_strs+2657)
#define SAVE_OPTS_DESC  (autogen_opt_strs+2663)
#define SAVE_OPTS_name  (autogen_opt_strs+2702)
#define LOAD_OPTS_DESC     (autogen_opt_strs+2712)
#define LOAD_OPTS_NAME     (autogen_opt_strs+2744)
#define NO_LOAD_OPTS_name  (autogen_opt_strs+2754)
#define LOAD_OPTS_pfx      (autogen_opt_strs+1268)
#define LOAD_OPTS_name     (NO_LOAD_OPTS_name + 3)
/*
 *  Declare option callback procedures
 */
#ifdef HAVE_DLOPEN
  static tOptProc doOptLoad_Functions;
#else /* not HAVE_DLOPEN */
# define doOptLoad_Functions NULL
#endif /* def/not HAVE_DLOPEN */
#ifdef SHELL_ENABLED
  static tOptProc doOptShell;
#else /* not SHELL_ENABLED */
# define doOptShell NULL
#endif /* def/not SHELL_ENABLED */
#ifdef SHELL_ENABLED
  static tOptProc doOptTimeout;
#else /* not SHELL_ENABLED */
# define doOptTimeout NULL
#endif /* def/not SHELL_ENABLED */
extern tOptProc
    config_dep,         optionBooleanVal,   optionNestedVal,
    optionNumericVal,   optionPagedUsage,   optionPrintVersion,
    optionResetOpt,     optionStackArg,     optionTimeDate,
    optionTimeVal,      optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptLib_Template,  doOptLoad_Scheme,   doOptLoop_Limit,
    doOptOverride_Tpl,  doOptSelect_Suffix, doOptTrace,
    doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Autogen Option Descriptions.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_TEMPL_DIRS,
     /* equiv idx, value */ 0, VALUE_OPT_TEMPL_DIRS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ TEMPL_DIRS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --templ-dirs */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ TEMPL_DIRS_DESC, TEMPL_DIRS_NAME, TEMPL_DIRS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_OVERRIDE_TPL,
     /* equiv idx, value */ 1, VALUE_OPT_OVERRIDE_TPL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OVERRIDE_TPL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --override-tpl */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptOverride_Tpl,
     /* desc, NAME, name */ OVERRIDE_TPL_DESC, OVERRIDE_TPL_NAME, OVERRIDE_TPL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_LIB_TEMPLATE,
     /* equiv idx, value */ 2, VALUE_OPT_LIB_TEMPLATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ LIB_TEMPLATE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --lib-template */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLib_Template,
     /* desc, NAME, name */ LIB_TEMPLATE_DESC, LIB_TEMPLATE_NAME, LIB_TEMPLATE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_BASE_NAME,
     /* equiv idx, value */ 3, VALUE_OPT_BASE_NAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BASE_NAME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --base-name */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ BASE_NAME_DESC, BASE_NAME_NAME, BASE_NAME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_DEFINITIONS,
     /* equiv idx, value */ 4, VALUE_OPT_DEFINITIONS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEFINITIONS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --definitions */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DEFINITIONS_DESC, DEFINITIONS_NAME, DEFINITIONS_name,
     /* disablement strs */ NOT_DEFINITIONS_name, NOT_DEFINITIONS_PFX },

  {  /* entry idx, value */ 5, VALUE_OPT_LOAD_SCHEME,
     /* equiv idx, value */ 5, VALUE_OPT_LOAD_SCHEME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_SCHEME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --load-scheme */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoad_Scheme,
     /* desc, NAME, name */ LOAD_SCHEME_DESC, LOAD_SCHEME_NAME, LOAD_SCHEME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_LOAD_FUNCTIONS,
     /* equiv idx, value */ 6, VALUE_OPT_LOAD_FUNCTIONS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_FUNCTIONS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --load-functions */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoad_Functions,
     /* desc, NAME, name */ LOAD_FUNCTIONS_DESC, LOAD_FUNCTIONS_NAME, LOAD_FUNCTIONS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_SKIP_SUFFIX,
     /* equiv idx, value */ 7, VALUE_OPT_SKIP_SUFFIX,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ SKIP_SUFFIX_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --skip-suffix */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aSkip_SuffixCantList,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ SKIP_SUFFIX_DESC, SKIP_SUFFIX_NAME, SKIP_SUFFIX_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_SELECT_SUFFIX,
     /* equiv idx, value */ 8, VALUE_OPT_SELECT_SUFFIX,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ SELECT_SUFFIX_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --select-suffix */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptSelect_Suffix,
     /* desc, NAME, name */ SELECT_SUFFIX_DESC, SELECT_SUFFIX_NAME, SELECT_SUFFIX_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_SOURCE_TIME,
     /* equiv idx, value */ 9, VALUE_OPT_SOURCE_TIME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SOURCE_TIME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --source-time */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SOURCE_TIME_DESC, SOURCE_TIME_NAME, SOURCE_TIME_name,
     /* disablement strs */ NOT_SOURCE_TIME_name, NOT_SOURCE_TIME_PFX },

  {  /* entry idx, value */ 10, VALUE_OPT_NO_FMEMOPEN,
     /* equiv idx, value */ 10, VALUE_OPT_NO_FMEMOPEN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_FMEMOPEN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --no-fmemopen */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ NO_FMEMOPEN_DESC, NO_FMEMOPEN_NAME, NO_FMEMOPEN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_EQUATE,
     /* equiv idx, value */ 11, VALUE_OPT_EQUATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ EQUATE_FLAGS, 0,
     /* last opt argumnt */ { EQUATE_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ EQUATE_DESC, EQUATE_NAME, EQUATE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_WRITABLE,
     /* equiv idx, value */ 12, VALUE_OPT_WRITABLE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ WRITABLE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --writable */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ WRITABLE_DESC, WRITABLE_NAME, WRITABLE_name,
     /* disablement strs */ NOT_WRITABLE_name, NOT_WRITABLE_PFX },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_DEBUG_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DOC_DEBUG_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_LOOP_LIMIT,
     /* equiv idx, value */ 14, VALUE_OPT_LOOP_LIMIT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOOP_LIMIT_FLAGS, 0,
     /* last opt argumnt */ { LOOP_LIMIT_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoop_Limit,
     /* desc, NAME, name */ LOOP_LIMIT_DESC, LOOP_LIMIT_NAME, LOOP_LIMIT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_SHELL,
     /* equiv idx, value */ 15, VALUE_OPT_SHELL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SHELL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --shell */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptShell,
     /* desc, NAME, name */ SHELL_DESC, SHELL_NAME, SHELL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_TIMEOUT,
     /* equiv idx, value */ 16, VALUE_OPT_TIMEOUT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TIMEOUT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --timeout */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTimeout,
     /* desc, NAME, name */ TIMEOUT_DESC, TIMEOUT_NAME, TIMEOUT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_TRACE,
     /* equiv idx, value */ 17, VALUE_OPT_TRACE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TRACE_FLAGS, 0,
     /* last opt argumnt */ { TRACE_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTrace,
     /* desc, NAME, name */ TRACE_DESC, TRACE_NAME, TRACE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_TRACE_OUT,
     /* equiv idx, value */ 18, VALUE_OPT_TRACE_OUT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TRACE_OUT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --trace-out */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TRACE_OUT_DESC, TRACE_OUT_NAME, TRACE_OUT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 19, VALUE_OPT_SHOW_DEFS,
     /* equiv idx, value */ 19, VALUE_OPT_SHOW_DEFS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SHOW_DEFS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --show-defs */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SHOW_DEFS_DESC, SHOW_DEFS_NAME, SHOW_DEFS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 20, VALUE_OPT_USED_DEFINES,
     /* equiv idx, value */ 20, VALUE_OPT_USED_DEFINES,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ USED_DEFINES_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --used-defines */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ USED_DEFINES_DESC, USED_DEFINES_NAME, USED_DEFINES_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_CONTROL_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DOC_CONTROL_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 22, VALUE_OPT_DEFINE,
     /* equiv idx, value */ 22, VALUE_OPT_DEFINE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ DEFINE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --define */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ DEFINE_DESC, DEFINE_NAME, DEFINE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 23, VALUE_OPT_UNDEFINE,
     /* equiv idx, value */ NOLIMIT, NOLIMIT,
     /* equivalenced to  */ INDEX_OPT_DEFINE,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ UNDEFINE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --undefine */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionUnstackArg,
     /* desc, NAME, name */ UNDEFINE_DESC, UNDEFINE_NAME, UNDEFINE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_DEPENDENCIES_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DOC_DEPENDENCIES_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 25, VALUE_OPT_MAKE_DEP,
     /* equiv idx, value */ 25, VALUE_OPT_MAKE_DEP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ MAKE_DEP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --make-dep */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ config_dep,
     /* desc, NAME, name */ MAKE_DEP_DESC, MAKE_DEP_NAME, MAKE_DEP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 26, VALUE_OPT_CORE,
     /* equiv idx, value */ 26, VALUE_OPT_CORE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CORE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --core */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ CORE_DESC, CORE_NAME, CORE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_RESET_OPTION, VALUE_OPT_RESET_OPTION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_RESET_OPTION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ RESET_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionResetOpt,
     /* desc, NAME, name */ RESET_DESC, NULL, RESET_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_USAGE, VALUE_OPT_USAGE,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_USAGE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ USAGE_DESC, NULL, USAGE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_SAVE_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SAVE_OPTS_DESC, NULL, SAVE_OPTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_LOAD_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ LOAD_OPTS_DESC, LOAD_OPTS_NAME, LOAD_OPTS_name,
     /* disablement strs */ NO_LOAD_OPTS_name, LOAD_OPTS_pfx }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Autogen Option Environment
 */
#define zPROGNAME       (autogen_opt_strs+2767)
#define zUsageTitle     (autogen_opt_strs+2775)
#define zRcName         (autogen_opt_strs+2924)
static char const * const apzHomeList[3] = {
    autogen_opt_strs+2916,
    autogen_opt_strs+2922,
    NULL };
#define zBugsAddr       (autogen_opt_strs+2935)
#define zExplain        (autogen_opt_strs+2971)
#define zDetail         (autogen_opt_strs+3043)
#define zFullVersion    (autogen_opt_strs+3157)
/* extracted from optcode.tlib near line 349 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */

static optArgBucket_t const originalAutogenDefaults[ OPTION_CT ] = {
    { NULL }, /* --templ-dirs */
    { NULL }, /* --override-tpl */
    { NULL }, /* --lib-template */
    { NULL }, /* --base-name */
    { NULL }, /* --definitions */
    { NULL }, /* --load-scheme */
    { NULL }, /* --load-functions */
    { NULL }, /* --skip-suffix */
    { NULL }, /* --select-suffix */
    { NULL }, /* --source-time */
    { NULL }, /* --no-fmemopen */
    { EQUATE_DFT_ARG },
    { NULL }, /* --writable */
    { NULL }, /* doc opt */
    { LOOP_LIMIT_DFT_ARG },
    { NULL }, /* --shell */
    { NULL }, /* --timeout */
    { TRACE_DFT_ARG },
    { NULL }, /* --trace-out */
    { NULL }, /* --show-defs */
    { NULL }, /* --used-defines */
    { NULL }, /* doc opt */
    { NULL }, /* --define */
    { NULL }, /* --undefine */
    { NULL }, /* doc opt */
    { NULL }, /* --make-dep */
    { NULL }, /* --core */
    { NULL }, /* resettable */
    { NULL }, /* version */
    { NULL }, /* help */
    { NULL }, /* more-help */
    { NULL }, /* usage-opt */
    { NULL }, /* save-opts */
    { NULL }  /* load-opts */
};
static void * const originalAutogenCookies[ OPTION_CT ] = {
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};


#define autogen_full_usage (NULL)

#define autogen_short_usage (NULL)

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the USAGE() macro.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    if ((pOptDesc->fOptState & OPTST_RESET) != 0)
        return;

    int ex_code = (pOptDesc->optIndex == INDEX_OPT_HELP)
        ? AUTOGEN_EXIT_SUCCESS : EX_USAGE;
    (void)pOptions;
    USAGE(ex_code);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the override-tpl option.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptOverride_Tpl(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 159 */
    pzTemplFileName = pOptDesc->optArg.argString;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the lib-template option.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLib_Template(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 180 */
    tTemplate* pT;
    procState = PROC_STATE_LIB_LOAD;
    pT = loadTemplate(pOptDesc->optArg.argString, NULL);
    unloadTemplate(pT);
    procState = PROC_STATE_OPTIONS;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the load-scheme option.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLoad_Scheme(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 269 */
    teProcState saveState = procState;
    char* pz;
    char  zPath[MAXPATHLEN];
    static char const * const apzSfx[] = { "scm", NULL };

    if (! SUCCESSFUL(
        findFile(pOptDesc->optArg.argString, zPath, apzSfx, NULL))) {

        usage_message(CANNOT_LOCATE_FMT,
                      pOptDesc->optArg.argString);
        /* NOTREACHED */
    }

    pz = aprf(LOAD_GUILE_FILE_FMT, zPath);
    procState = PROC_STATE_GUILE_PRELOAD;
    (void)ag_scm_c_eval_string_from_file_line(
                   pz, __FILE__, __LINE__);
    free(pz);
    procState = saveState;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the load-functions option, when HAVE_DLOPEN is #define-d.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef HAVE_DLOPEN
static void
doOptLoad_Functions(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 319 */
    void* hdl = dlopen(
        pOptDesc->optArg.argString, RTLD_NOW|RTLD_GLOBAL);
    init_proc_t* proc;

    if (hdl == NULL) {
        char const* pzErr = dlerror();
        fprintf(stderr, DLOPEN_ERROR_FMT,
                pOptDesc->optArg.argString, errno, pzErr);
        exit(EXIT_FAILURE);
    }
    proc = (init_proc_t*)dlsym(hdl, "scm_init");
    if (proc == NULL) {
        fprintf(stderr, SYM_NOT_FOUND_FMT,
                pOptDesc->optArg.argString);
    }
    else (*proc)();
}
#endif /* defined HAVE_DLOPEN */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the select-suffix option.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptSelect_Suffix(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 381 */
    char const * arg = pOptDesc->optArg.argString;
    if ((arg != NULL) && (*arg != NUL))
        (void)do_suffix(arg, NULL, -1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the loop-limit option.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLoop_Limit(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[2] = {
        { -1, LONG_MIN },  { 1, 0x1000000 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    if ((pOptDesc->fOptState & OPTST_RESET) != 0)
        return;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 2; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 2);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the shell option, when SHELL_ENABLED is #define-d.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef SHELL_ENABLED
static void
doOptShell(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 512 */
    pzShellProgram = pOptDesc->optArg.argString;
}
#endif /* defined SHELL_ENABLED */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the timeout option, when SHELL_ENABLED is #define-d.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef SHELL_ENABLED
static void
doOptTimeout(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 3600 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    if ((pOptDesc->fOptState & OPTST_RESET) != 0)
        return;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}
#endif /* defined SHELL_ENABLED */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the trace option.
 *
 * @param pOptions the autogen options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptTrace(tOptions* pOptions, tOptDesc* pOptDesc)
{

/* extracted from optmain.tlib near line 834 */
    static char const * const azNames[7] = {
        autogen_opt_strs+3184,  autogen_opt_strs+3192,  autogen_opt_strs+3206,
        autogen_opt_strs+3219,  autogen_opt_strs+3229,  autogen_opt_strs+3242,
        autogen_opt_strs+3254 };

    if (pOptions <= OPTPROC_EMIT_LIMIT) {
        (void) optionEnumerationVal(pOptions, pOptDesc, azNames, 7);
        return; /* protect AutoOpts client code from internal callbacks */
    }
    if ((pOptDesc->fOptState & OPTST_RESET) != 0)
        return;

    pOptDesc->optArg.argEnum =
        optionEnumerationVal(pOptions, pOptDesc, azNames, 7);

}
/* extracted from optmain.tlib near line 1093 */

/**
 * Print a usage message with a format and va_list argument.
 * The USAGE exit macro is then invoked to print the error usage text
 * (somewhat abbreviated) and then exit.
 *
 * @param fmt the format string
 * @param ap  the var-arg list.
 */
void
vusage_message(char const * fmt, va_list ap)
{
    char const * er_fmt = _("%s usage error:\n");
    fprintf(stderr, er_fmt, autogenOptions.pzProgName);
    vfprintf(stderr, fmt, ap);
    USAGE(AUTOGEN_EXIT_OPTION_ERROR);
    /* NOTREACHED */
}

/**
 * Print a usage message with a format and a variable argument list. 
 * vusage_message() is called to do the work.
 *
 * @param fmt the format string
 * @param ap  the var-arg list.
 */
void
usage_message(char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vusage_message(fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

#ifndef  WITH_PACKAGER
# define autogen_packager_info NULL
#else
static char const autogen_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport autogen bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif

tOptions autogenOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NEGATIONS
    + OPTPROC_ENVIRON ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    34 /* full option count */, 27 /* user option count */,
    autogen_full_usage, autogen_short_usage,
    originalAutogenDefaults, originalAutogenCookies,
    PKGDATADIR, autogen_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

static char*
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(AUTOGEN_EXIT_OPTION_ERROR);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/*
 *  This invokes the translation code (e.g. gettext(3)).
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &autogenOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        autogenOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* opts.c ends here */
