---
# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

ignore:
  - src/gdb/*/*/*/build/*.build/Debug/*.build/all-product-headers.yaml
  - src/tk/macosx/build/*.build/Development/*.build/all-product-headers.yaml

rules:
  float-values: enable
  indentation:
    ignore:
      - .github/workflows/apple-gdb-1824-macos.yml
      - .github/workflows/codeql.yml
  # some lines might be really long in this repo, and I don't feel like
  # figuring out how to break them up:
  line-length:
    max: 99
    level: warning
    ignore:
      - .github/workflows/apple-gdb-1824*.yml
      - .github/workflows/codeql.yml
      - .travis.yml
  octal-values: enable
  truthy: disable
