/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DBGDataType.h"

@interface DBGGDBDataType : DBGDataType
{
    int _typeCode;
}

@property(readonly) int typeCode; // @synthesize typeCode=_typeCode;
- (BOOL)isUnknownType;
- (BOOL)isPointer;
- (id)initWithTypename:(id)arg1 withTypeCode:(int)arg2;

@end

