/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/DBGGDBByteStream.h>

#import "DBGGDBCharacterStreamConsuming-Protocol.h"
#import "DBGGDBStreamConsumerRetaining-Protocol.h"

@interface DBGGDBUTF8EncoderFilter : DBGGDBByteStream <DBGGDBCharacterStreamConsuming, DBGGDBStreamConsumerRetaining>
{
}

- (void)stream:(id)arg1 processCharacters:(id)arg2;
- (void)streamDidEnd:(id)arg1;

@end

