/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/DBGGDBByteStream.h>

#import "DBGGDBByteStreamConsuming-Protocol.h"

@class NSConditionLock, NSFileHandle, NSMutableArray, NSMutableData, NSString;

@interface DBGGDBPTYDeviceByteStream : DBGGDBByteStream <DBGGDBByteStreamConsuming>
{
    int _masterFD;
    int _slaveFD;
    NSFileHandle *_masterFileHandle;
    NSString *_slaveDeviceName;
    NSFileHandle *_slaveFileHandle;
    BOOL _controlOverReading;
    BOOL _receivedLastDataBuffer;
    int _fromSignalPipeFD;
    int _toSignalPipeFD;
    BOOL _watcherThreadRunning;
    NSConditionLock *_queueLock;
    NSMutableArray *_queue;
    NSMutableData *_accumulator;
    unsigned long long _bufferedDataLength;
    unsigned long long _stats_numBytesSent;
    unsigned long long _stats_numBytesRead;
}

- (id)fileHandleForMasterDevice;
- (int)masterDeviceFD;
- (id)fileHandleForSlaveDevice;
- (id)slaveDeviceName;
- (void)stream:(id)arg1 processBytes:(id)arg2;
- (void)streamDidEnd:(id)arg1;
- (void)sendStreamDidEnd;
- (void)closePTY;
- (void)_stopPTYWatcherThread;
- (void)_ptyWatcherThreadDidExit;
- (void)_processPtyData;
- (void)_watchPTY;
- (void)_setupPTYWatcherThread;
- (void)finalize;
- (void)dealloc;
- (id)initWithControlOverReading;
- (id)init;

@end

