/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_UnicharFetchResult.h>

@interface PBXGDB_WCharFetchResult : PBXGDB_UnicharFetchResult
{
}

- (void)processStringData;

@end

