/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_CommandSequence.h>

@class IDEBreakpoint, PBXGDB_BreakpointController, PBXGDB_BreakpointInfo;

@interface PBXGDB_BaseBreakpointSequence : PBXGDB_CommandSequence
{
    PBXGDB_BreakpointController *_breakpointController;
    PBXGDB_BreakpointInfo *_breakpointInfo;
    IDEBreakpoint *_breakpoint;
    long long _numCommands;
}

+ (id)_symbolNameFromGDBAtParameter:(id)arg1;
@property(retain) IDEBreakpoint *breakpoint; // @synthesize breakpoint=_breakpoint;
- (BOOL)interruptIfNeeded;
- (void)didFinish;
- (id)breakpointInfo;
- (void)setBreakpointInfo:(id)arg1;
- (id)breakpointController;
- (void)setBreakpointController:(id)arg1;

@end

