/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MICommand.h>

@interface PBXGDB_MISelectThreadCommand : PBXGDB_MICommand
{
    PBXGDB_MICommand *_cmdToPost;
}

@property(retain) PBXGDB_MICommand *nextCommandToPost; // @synthesize nextCommandToPost=_cmdToPost;
- (void)setSelectedThreadId:(long long)arg1 nextCommandToPost:(id)arg2;

@end

