/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_BaseBreakpointSequence.h>

@interface PBXGDB_NewBreakpointSequence : PBXGDB_BaseBreakpointSequence
{
}

+ (id)createBreakpointLoationForBreakpoint:(id)arg1 fromListItem:(id)arg2 inDebugSession:(id)arg3;
- (void)execute;
- (void)_breakpointWasCreated:(id)arg1;
- (id)_handleBreakpointResolvedToLocation:(id)arg1;
- (BOOL)handleErrorForMICommand:(id)arg1;

@end

