/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MIBaseVarObjCommand.h>

@class NSMutableString;

@interface PBXGDB_MIUpdateVarObjListCommand : PBXGDB_MIBaseVarObjCommand
{
    NSMutableString *_varObjNameListString;
}

- (void)didFinishWithResultList:(id)arg1;
- (void)endList;
- (void)appendVarObjName:(id)arg1;
- (void)appendVarObjNameArray:(id)arg1;
- (id)varObjNameListString;

@end

