/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DBGGDBLineStreamConsuming-Protocol.h"

@class NSCharacterSet, NSMutableString, NSString, PBXGDB_MIController, PBXGDB_MIResultList;

@interface PBXGDB_MIParser : NSObject <DBGGDBLineStreamConsuming>
{
    PBXGDB_MIController *_miController;
    NSCharacterSet *_digitCharSet;
    NSMutableString *_errorStateString;
    NSMutableString *_parseBuffer;
    BOOL _incompleteParsing;
    unsigned long long _parseBufferLength;
    unsigned long long _currentCharIndex;
    NSString *_tmpSubstring;
    BOOL _sentGDBDidStart;
    unsigned long long _sequenceNumberForShellCmd;
    BOOL _startTrackingShellCmd;
    NSMutableString *_parsedOutputText;
    unsigned long long _parsedSequenceNumber;
    PBXGDB_MIResultList *_parsedResultList;
}

@property unsigned long long sequenceNumberForShellCmd; // @synthesize sequenceNumberForShellCmd=_sequenceNumberForShellCmd;
- (BOOL)hasParsedOutputText;
- (unsigned long long)parsedSequenceNumber;
- (id)parsedOutputText;
- (id)parsedResultList;
- (void)streamDidEnd:(id)arg1;
- (void)stream:(id)arg1 processLine:(id)arg2;
- (id)parseAndApproveOutputFromDebugger:(id)arg1;
- (BOOL)parseMILine:(id)arg1;
- (void)_parseMILine:(id)arg1;
- (void)_processCurrentLine;
- (void)_saveCurrentLineAsOutputText;
- (void)_processCurrentLineAndOutputText:(BOOL)arg1;
- (void)parseMITuple:(id)arg1;
- (void)parseMIList:(id)arg1;
- (BOOL)_continueParsingMIListOrTuple;
- (id)parseMIListItem;
- (id)parseEscapedQuotedString;
- (id)_reallyParseEscapedQuotedStringWithInitialString:(id)arg1;
- (void)setCurrentCharacterIndex:(unsigned long long)arg1;
- (unsigned long long)currentCharacterIndex;
- (unsigned short)nextCharacter;
- (unsigned short)currentCharacter;
- (void)setParseBuffer:(id)arg1;
- (void)resetForParsingASingleLine;
- (id)tmpSubstring;
- (void)setTmpSubstringToRange:(struct _NSRange)arg1;
- (void)raiseError:(id)arg1;
- (id)errorStateString;
- (id)miController;
- (id)description;
- (void)dealloc;
- (id)initWithMIController:(id)arg1;

@end

