/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_BaseBreakpointSequence.h>

@class NSString;

@interface PBXGDB_BreakpointConditionSequence : PBXGDB_BaseBreakpointSequence
{
    NSString *_conditionString;
    long long _breakpointNum;
}

+ (id)sequenceWithCondition:(id)arg1 forBreakpointNum:(long long)arg2;
- (void)execute;
- (void)_breakpointConditionSet:(id)arg1;
- (BOOL)handleErrorForMICommand:(id)arg1;

@end

