/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_Controller.h>

@class PBXGDB_DescriptionDataValue;

@interface PBXGDB_DataValueController : PBXGDB_Controller
{
    PBXGDB_DescriptionDataValue *_registerDV;
}

- (void)enqueuePOSequenceForDataValue:(id)arg1;
- (void)enqueuePrintDescriptionSequenceForDataValue:(id)arg1;
- (void)enqueueSequenceForContainerDataValue:(id)arg1 cloneDVByPathExpression:(id)arg2;
- (void)enqueueSequenceForContainerDataValue:(id)arg1 createNewDVWithExpression:(id)arg2 locationSpecifier:(id)arg3;
- (void)enqueueSequenceForContainerDataValue:(id)arg1 createNewDVWithExpression:(id)arg2 bindToFrame:(BOOL)arg3;
- (void)enqueueSequenceForContainerDataValue:(id)arg1 createNewDVWithExpression:(id)arg2 blockStartAddress:(id)arg3;
- (void)enqueueGetPathExpressionSequenceForDataValue:(id)arg1;
- (void)enqueueSetFormatSequenceForDataValue:(id)arg1 newFormat:(int)arg2;
- (void)enqueueSetValueSequenceForDataValue:(id)arg1 newValue:(id)arg2;
- (void)enqueueGetChildrenSequenceForDataValue:(id)arg1;
- (void)enqueueDeleteChildrenSequenceForDataValue:(id)arg1 freeVarObjs:(BOOL)arg2;
- (void)enqueueDeleteSequenceForDataValue:(id)arg1;
- (void)enqueueUpdateSequenceForDataValue:(id)arg1;
- (void)enqueueGetFrameSymbolsSequenceForDataValue:(id)arg1;
- (void)enqueueGetFrameRegisterSequenceForDataValue:(id)arg1;
- (void)_initSequence:(id)arg1 dataValue:(id)arg2;

@end

