/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_BaseThreadSequence.h>

@class PBXGDB_MICommand;

@interface PBXGDB_UntilSequence : PBXGDB_BaseThreadSequence
{
    PBXGDB_MICommand *_miCommand;
}

+ (id)sequenceWithFile:(id)arg1 lineNumber:(unsigned long long)arg2;
- (id)miCommand;
- (void)setMICommand:(id)arg1;
- (void)_resultAllThreadsRunning:(id)arg1;
- (void)execute;

@end

