/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_CommandSequence.h>

@class IDEBreakpoint, IDEBreakpointAction;

@interface PBXGDB_BreakpointActionEvaluateExpressionSequence : PBXGDB_CommandSequence
{
    IDEBreakpoint *_breakpoint;
    IDEBreakpointAction *_action;
    id _lastCmd;
}

+ (id)sequenceWithBreakpoint:(id)arg1 andAction:(id)arg2;
- (BOOL)handleErrorForMICommand:(id)arg1;
- (void)breakpointActionExpressionEvaluated:(id)arg1;
- (void)execute;

@end

