/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class PBXGDB_SequenceController;

@interface PBXGDB_CommandSequence : NSObject
{
    PBXGDB_SequenceController *_controller;
    Class _currentSafetyCheckClass;
    BOOL _hasTimedOut;
    BOOL _hasTurnedSchedulerLockingOff;
    BOOL _transient;
    BOOL _canPurgeTransientSequences;
}

+ (void)initialize;
@property BOOL canPurgeTransientSequences; // @synthesize canPurgeTransientSequences=_canPurgeTransientSequences;
@property(getter=isTransient) BOOL transient; // @synthesize transient=_transient;
- (id)foundationDebugSession;
- (long long)_safteyCheckThreadID;
- (void)_didCheckSafety:(id)arg1;
- (void)_cleanUpSchedulerState:(SEL)arg1;
- (void)safetyCheckSucceeded;
- (void)safetyCheckFailed;
- (void)_verifySafetyCmd:(id)arg1;
- (void)_privateDoCheckSaftey;
- (void)_privateCheckSafety;
- (void)_checkSafety:(id)arg1;
- (void)evaluationSafetyCheck;
- (id)safetyCheckClasses;
- (BOOL)needsEvaluationSafetyCheck;
- (BOOL)interruptIfNeeded;
- (void)didFinish;
- (void)execute;
- (id)gdbAdaptor;
- (id)sequenceController;
- (void)setSequenceController:(id)arg1;
- (BOOL)handleErrorForMICommand:(id)arg1;
- (double)timeOutPeriod;
- (void)timedOut;

@end

