/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_CommandSequence.h>

@class NSString;

@interface PBXGDB_ConsoleSequence : PBXGDB_CommandSequence
{
    NSString *_stringToComplete;
    id _resultHandler;
}

- (void)execute;
- (void)setStringToComplete:(id)arg1 resultHandler:(id)arg2;
- (void)_gotCompletion:(id)arg1;

@end

