/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEBreakpoint, NSMutableArray;

@interface PBXGDB_BreakpointInfo : NSObject
{
    IDEBreakpoint *_breakpoint;
    NSMutableArray *_gdbContexts;
    long long _unresolvedContextCount;
}

@property(retain) IDEBreakpoint *breakpoint; // @synthesize breakpoint=_breakpoint;
- (id)contextWithGDBBreakpointNumber:(long long)arg1;
- (long long)gdbBreakpointNumber;
- (BOOL)hasUnresolvedContexts;
- (void)decrementUnresolvedCount;
- (void)incrementUnresolvedCount;
- (void)removeGDBContextWithGDBNumber:(long long)arg1;
- (void)addGDBContext:(id)arg1;
- (void)addNewContextWithGDBNumber:(long long)arg1 address:(id)arg2 shlibPath:(id)arg3;
- (id)gdbContexts;
- (id)init;

@end

