/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_EvaluationSequence.h>

@class NSData, PBXLSAddressValue;

@interface PBXGDB_FetchStringSequence : PBXGDB_EvaluationSequence
{
    PBXLSAddressValue *_baseAddressValue;
    NSData *_resultMemoryData;
    unsigned long long _bytesPerCharacter;
    unsigned long long _numberOfCharacters;
    BOOL _resultStatus;
    BOOL _stringWasTruncated;
}

- (void)execute;
- (void)fetchStringBuffer;
- (void)gotStringMemory:(id)arg1;
- (void)didFinishWithData:(id)arg1;
- (void)didFinishWithNoData;
- (BOOL)handleErrorForMICommand:(id)arg1;
- (BOOL)resultStatus;
- (void)setResultStatus:(BOOL)arg1;
- (id)resultMemoryData;
- (void)setResultMemoryData:(id)arg1;
- (unsigned long long)numberOfCharactersForStringBuffer;
- (unsigned long long)numberOfCharacters;
- (void)setNumberOfCharacters:(unsigned long long)arg1;
- (unsigned long long)bytesPerCharacter;
- (void)setBytesPerCharacter:(unsigned long long)arg1;
- (id)stringBufferAddressExpression;
- (id)stringBufferAddressValue;
- (id)baseAddressValue;
- (void)setBaseAddress:(id)arg1;
- (void)dealloc;

@end

