/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_CommandSequence.h>

@interface PBXGDB_FixAndContinueIsSupportedSequence : PBXGDB_CommandSequence
{
    BOOL _fixAndContinueIsSupported;
}

- (void)didFinish;
- (void)execute;
- (void)_gotVerifyFixAndContinue:(id)arg1;
- (void)_fetchStatus;
- (void)_gotFixAndContinueStatus:(id)arg1;
- (BOOL)handleErrorForMICommand:(id)arg1;
- (id)commandString;

@end

