/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_EvaluationSequence.h>

@class NSString;

@interface PBXGDB_ExpressionEvalSequence : PBXGDB_EvaluationSequence
{
    NSString *_exprString;
    NSString *_resultString;
}

- (void)execute;
- (void)_gotExpressionResult:(id)arg1;
- (id)expresssionToEvaluate;
- (void)setExpressionToEvaluate:(id)arg1;
- (id)resultString;
- (BOOL)handleErrorForMICommand:(id)arg1;

@end

