/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_CommandSequence.h>

@class NSString, PBXGDB_DataValue2;

@interface PBXGDB_BaseDataValueSequence : PBXGDB_CommandSequence
{
    PBXGDB_DataValue2 *_dataValue;
    long long _outstandingMICommandsCount;
    NSString *_expressionString;
}

+ (void)initialize;
- (long long)_safteyCheckThreadID;
- (void)timedOut;
- (double)timeOutPeriod;
- (void)subSequenceGetPathExpressionForDataValue:(id)arg1;
- (void)_gotPathExpression:(id)arg1;
- (void)didGetPathExpression;
- (void)subSequenceUpdateDataValues:(id)arg1;
- (void)_gotResultVarObjUpdated:(id)arg1;
- (BOOL)handleErrorForMICommand:(id)arg1;
- (void)setDataValue:(id)arg1 fromCreateVarObjCommand:(id)arg2;
- (id)createVarObjDataValue;
- (id)createVarObjDataValuesFromCommand:(id)arg1 parentDV:(id)arg2 isTrigger:(BOOL)arg3 automaticallyAddToParent:(BOOL)arg4;
- (id)createVarObjDataValuesFromCommand:(id)arg1 parentDV:(id)arg2 isTrigger:(BOOL)arg3;
- (id)createVarObjDataValuesFromCommand:(id)arg1 parentDV:(id)arg2;
- (void)setDataValue:(id)arg1 fromVarObjCommand:(id)arg2;
- (void)subSequenceGetValuesForDataValues:(id)arg1;
- (void)_gotResultVarObjValue:(id)arg1;
- (void)_setupTypeInfoForDV:(id)arg1 fromBaseTypeExpressionString:(id)arg2 dynamicTypeExpressionString:(id)arg3 typeCode:(int)arg4;
- (void)postCommandWithGroupFrameContext:(id)arg1;
- (id)containingDataValue;
- (id)varObjDataValue;
- (id)dataValue;
- (void)setDataValue:(id)arg1;
- (void)dealloc;
- (id)init;

@end

