/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXLSModel.h>

@class DBGGDBThread, NSString;

@interface PBXLSThread : PBXLSModel
{
    DBGGDBThread *_foundationThread;
    NSString *_lastReasonStopped;
    int _threadState;
    unsigned long long _handle;
    long long _threadStateStatus;
    NSString *_name;
    NSString *_queueName;
    BOOL _didTransitionToSuspended;
    int _stopReason;
}

@property int stopReason; // @synthesize stopReason=_stopReason;
@property(copy) NSString *lastReasonStopped; // @synthesize lastReasonStopped=_lastReasonStopped;
@property(copy) NSString *queueName; // @synthesize queueName=_queueName;
@property(copy) NSString *name; // @synthesize name=_name;
@property int threadState; // @synthesize threadState=_threadState;
@property(retain) DBGGDBThread *foundationThread; // @synthesize foundationThread=_foundationThread;
- (void)requestSuspend;
- (void)requestResume;
- (void)requestContinue;
- (void)requestStepOverOnThread;
- (void)requestStepInOnThread;
- (void)requestStepUntilLineNumber:(unsigned long long)arg1;
- (void)requestStepOut;
- (void)requestStepOver;
- (void)requestStepInto;
- (void)requestStepOverInstruction;
- (void)requestStepIntoInstruction;
- (void)setStackFramesWithoutKVO:(id)arg1;
- (void)requestUpdateStack;
- (void)debuggerDidUpdateStack:(id)arg1;
- (void)removeAllChildren;
- (void)insertChild:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)debugger:(id)arg1 setThreadState:(int)arg2 status:(long long)arg3;
- (void)processDidUpdateAndDoUpdate:(BOOL)arg1;
- (long long)threadStateStatus;
- (void)invalidateFrameDataValues;
- (void)invalidateFrameContainerValue;
- (int)stackValidityStatus;
- (void)setStackValidityStatus:(int)arg1;
- (void)setCurrentStackFrame:(id)arg1;
- (id)stackFrames;
- (BOOL)didTransitionToSuspended;
- (void)clearDidTransitionToSuspended;
- (void)debuggerDelete:(id)arg1;
- (id)parentThreadGroup;
- (id)displayStatus;
- (id)description;
- (unsigned long long)handle;
- (void)setHandle:(unsigned long long)arg1;
- (id)initWithDebugger:(id)arg1;

@end

