# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "gdb", "~> 1.0"

gem "segv-handler-gdb", "~> 1.0"

gem "rgdb", "~> 0.0.1"

gem "gdbdump", "~> 0.9.4"

gem "gdbruby", "~> 0.0.2"
