#!/bin/ksh

# First source /app/appserver
if test -e /app/appserver; then
	echo "Sourcing /app/appserver..."
	. /app/appserver
else
	echo "This script requires /app/appserver to be present."
	exit 1
fi

# Exec the executable.
if test -z "$APPROOT"; then
	echo "This script requires APPROOT to be set."
	exit 1
fi

exec $APPROOT/usr/contrib/bin/$(basename $0) "$@"
