/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DBGThread.h"

@class PBXLSThread;

@interface DBGGDBThread : DBGThread
{
    PBXLSThread *_PBXThread;
    BOOL _shouldSetCurrentStackFrame;
}

@property(retain, nonatomic) PBXLSThread *PBXThread; // @synthesize PBXThread=_PBXThread;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)requestUnsuspend;
- (void)requestSuspend;
- (void)requestStackFrames:(unsigned long long)arg1 resultQueue:(struct dispatch_queue_s *)arg2 resultHandler:(id)arg3;
- (void)refreshStackFramesAndSetFirstFrame;
- (BOOL)refreshStackFrames;
- (void)updateStackFrames;
- (id)stackFrameFromPBXStackFrame:(id)arg1 frameNumber:(id)arg2 shouldCreate:(BOOL)arg3;
- (void)_extractInfoForStackFrame:(id)arg1 fromPBXStackFrame:(id)arg2;
- (id)_framePointerPBXStackFrame:(id)arg1;
- (id)initWithParentProcess:(id)arg1 uniqueID:(id)arg2 PBXThread:(id)arg3;

@end

