/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DBGDebugSession.h"

@class DBGGDBLauncher, PBXLSDebuggingSession, PBXLSProcess;

@interface DBGGDBSession : DBGDebugSession
{
    PBXLSDebuggingSession *_PBXDebugSession;
}

+ (id)dataValueFormatForTag:(unsigned long long)arg1;
+ (id)_naturalFormat;
+ (id)defaultFormat;
+ (id)_gdbDataValueFormats;
+ (BOOL)_inputEndsInFormatRequest:(id)arg1;
@property(readonly) PBXLSDebuggingSession *PBXDebugSession; // @synthesize PBXDebugSession=_PBXDebugSession;
- (id)logSuffix;
- (id)logFilename;
- (void)completeString:(id)arg1 resultHandler:(id)arg2;
- (void)printDescriptionOfDataValueToConsole:(id)arg1 runAllThreads:(BOOL)arg2;
- (id)supportedDataValueFormatsForDataValue:(id)arg1;
- (BOOL)shouldAcceptFromDebugSession:(id)arg1 error:(id *)arg2;
- (BOOL)shouldRelinquishToDebugSession:(id)arg1 error:(id *)arg2;
- (void)requestMovePCInStackFrame:(id)arg1 toLineNumber:(unsigned long long)arg2;
- (void)loadDebugSymbolsForSharedLibrary:(id)arg1;
- (BOOL)supportsPCAnnotationDragging;
- (void)executeDebuggerCommand:(id)arg1 threadID:(unsigned long long)arg2 frameID:(unsigned long long)arg3;
- (void)requestContinueToLocation:(id)arg1 inContext:(struct NSObject *)arg2;
- (void)requestStepIntoCallSymbol:(id)arg1 atLocation:(id)arg2 inContext:(struct NSObject *)arg3;
- (void)requestStepOverSuspendOtherThreads:(struct NSObject *)arg1;
- (void)requestStepInSuspendOtherThreads:(struct NSObject *)arg1;
- (void)requestStepOverInstruction:(struct NSObject *)arg1;
- (void)requestStepIntoInstruction:(struct NSObject *)arg1;
- (void)requestStop:(struct NSObject *)arg1;
- (void)requestContinue:(struct NSObject *)arg1;
- (void)requestPause:(struct NSObject *)arg1;
- (void)requestStepOut:(struct NSObject *)arg1;
- (void)requestStepOverLine:(struct NSObject *)arg1;
- (void)requestStepIn:(struct NSObject *)arg1;
- (id)PBXThreadForCurrentThread;
@property(readonly) DBGGDBLauncher *launcher;
@property(readonly) PBXLSProcess *PBXProcess;
- (void)cleanUp;
- (id)initWithDebugLauncher:(id)arg1 PBXDebugSession:(id)arg2;

@end

