/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_VarObjDataValue2.h>

@interface PBXGDB_ArrayDataValue : PBXGDB_VarObjDataValue2
{
}

- (void)reset;
- (id)varObjName;
- (void)setStringValue:(id)arg1;
- (void)requestGetChildren;
- (void)requestSecondaryUpdate;
- (BOOL)needsSecondaryUpdate;
- (BOOL)alwaysUpdate;
- (BOOL)usesSyntheticChildren;
- (BOOL)hasChildren;
- (void)requestUpdateContainer;
- (void)requestNewContainer;
- (BOOL)containerNeedsUpdate;
- (BOOL)containerIsInitialized;

@end

