/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MIBaseBreakpointCommand.h>

@interface PBXGDB_MIBreakpointCommandCommand : PBXGDB_MIBaseBreakpointCommand
{
}

+ (id)GDBCommand;
+ (id)commandWithCommand:(id)arg1 forBreakpointNum:(long long)arg2;

@end

