/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class PBXGDB_Adaptor;

@interface PBXGDB_Controller : NSObject
{
    PBXGDB_Adaptor *_gdbAdaptor;
}

- (id)gdbAdaptor;
- (void)setGDBAdaptor:(id)arg1;

@end

