/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MICommand.h>

@class NSArray, NSMutableString, NSString, PBXGDB_MIResultList;

@interface PBXGDB_MIStackFramesCommand : PBXGDB_MICommand
{
    NSMutableString *_fileNameBuffer;
    NSString *_pathSeparator;
    NSArray *_framesListItems;
    unsigned long long _currentFrameIndex;
    PBXGDB_MIResultList *_currentFrameItems;
    long long _startIndex;
    long long _stopIndex;
}

@property(readonly) long long stopIndex; // @synthesize stopIndex=_stopIndex;
@property(readonly) long long startIndex; // @synthesize startIndex=_startIndex;
@property(readonly) NSString *currentModulePath;
- (long long)currentFrameLineNumber;
- (id)currentFrameFileName;
- (id)currentFrameFunctionName;
- (unsigned long long)currentFrameFPAddress;
- (unsigned long long)currentFrameIPAddress;
- (long long)currentFrameIndex;
- (void)didFinishWithResultList:(id)arg1;
- (BOOL)nextFrame;
- (void)setGetAllFrames;
- (void)setStartFrameIndex:(long long)arg1 stopFrameIndex:(long long)arg2;
- (id)initWithSequenceNumber:(unsigned long long)arg1;

@end

