/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXLSType.h>

@class NSMutableSet;

@interface PBXGDB_CType : PBXLSType
{
    NSMutableSet *_subclassTypes;
    PBXGDB_CType *_superclassType;
}

- (id)summaryDescriptionDictionaryViaSuperclass;
- (id)superclassType;
- (void)setSuperclassType:(id)arg1;
- (void)addSubclassType:(id)arg1;
- (void)dealloc;
- (id)initWithController:(id)arg1;
- (id)init;

@end

