/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_BaseCPPExceptionHandlingSequence.h>

@interface PBXGDB_StopOnCPPThrowSequence : PBXGDB_BaseCPPExceptionHandlingSequence
{
}

- (void)sendRegex:(id)arg1;
- (void)setupCommand:(id)arg1;
- (void)execute;

@end

