/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class PBXGDB_MIStoppedStateDetail;

@interface PBXGDB_MIStoppedState : NSObject <NSCopying>
{
    int reason;
    long long currentThreadNumber;
    int processID;
    BOOL fatal;
    PBXGDB_MIStoppedStateDetail *detail;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

