/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_BaseDescription.h>

@class NSString;

@interface PBXGDB_ThreadDescription : PBXGDB_BaseDescription
{
    NSString *_queueName;
}

@property(copy) NSString *queueName; // @synthesize queueName=_queueName;

@end

