/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MIBaseBreakpointCommand.h>

@interface PBXGDB_MICreateFileBreakpointCommand : PBXGDB_MIBaseBreakpointCommand
{
}

- (void)setFileName:(id)arg1 lineNumber:(unsigned long long)arg2 condition:(id)arg3 ignoreCount:(unsigned long long)arg4 futureBreak:(BOOL)arg5 resolveMultipleMatches:(BOOL)arg6 temporary:(BOOL)arg7 shlib:(id)arg8;
- (void)setFileName:(id)arg1 lineNumber:(unsigned long long)arg2 futureBreak:(BOOL)arg3 resolveMultipleMatches:(BOOL)arg4 temporary:(BOOL)arg5 shlib:(id)arg6;

@end

