/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MISetSharedLibraryBaseCommand.h>

@interface PBXGDB_MISetSharedLibraryImageSymbolsLevelCommand : PBXGDB_MISetSharedLibraryBaseCommand
{
}

- (void)setSymbolsLevel:(int)arg1 forImageAtIndex:(long long)arg2;

@end

