/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_FetchStringSequence.h>

@class NSData;

@interface PBXGDB_FetchCharacterSquence : PBXGDB_FetchStringSequence
{
    NSData *data;
}

@property(retain) NSData *data; // @synthesize data;
- (void)execute;
- (void)fetchCharacter;

@end

