/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXLSDynamicLinkerImage.h>

@class PBXGDB_Adaptor;

@interface PBXGDB_DynamicLinkerImage : PBXLSDynamicLinkerImage
{
    long long _idNumber;
    PBXGDB_Adaptor *_gdbAdaptor;
}

+ (void)appendSharedLibraryImagesFrom:(id)arg1 adaptor:(id)arg2;
+ (void)_appendSharedLibraryEntryFrom:(id)arg1 adaptor:(id)arg2;
+ (int)_debugSymbolsLoadState:(id)arg1;
- (id)gdbAdaptor;
- (void)setGDBAdaptor:(id)arg1;
- (long long)idNumber;
- (void)setIDNumber:(long long)arg1;

@end

