/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MICommand.h>

@interface PBXGDB_MIStopOnCPPExceptionCommand : PBXGDB_MICommand
{
    BOOL enable;
    BOOL throwCommand;
}

- (id)GDBCommandString;
- (void)setIsThrowCommand:(BOOL)arg1;
- (void)setEnabled:(BOOL)arg1;

@end

