/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface PBXGDB_BaseDescription : NSObject
{
    NSString *_name;
    long long _index;
}

- (long long)index;
- (void)setIndex:(long long)arg1;
- (id)name;
- (void)setName:(id)arg1;
- (id)description;

@end

