/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class IDEWatchpointNotificationInfo, NSString;

@interface PBXGDB_MIStoppedStateDetail : NSObject <NSCopying>
{
    NSString *signalName;
    int exitCode;
    long long breakpointHasCommand;
    long long breakpointNumber;
    NSString *exceptionName;
    BOOL isThrow;
    long long breakpointHitCount;
    IDEWatchpointNotificationInfo *watchpointInfo;
}

- (id)copyWithZone:(struct _NSZone *)arg1;

@end

