/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_BaseSharedLibrarySequence.h>

@interface PBXGDB_SetupSharedLibrarySequence : PBXGDB_BaseSharedLibrarySequence
{
}

- (void)execute;
- (int)_checkSymbolsLevel:(int)arg1 usingCachedSymFiles:(BOOL)arg2;
- (void)_applyLoadRules:(id)arg1;
- (void)_done:(id)arg1;
- (BOOL)interruptIfNeeded;

@end

