/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_Controller.h>

@class PBXGDB_MIStoppedState;

@interface PBXGDB_ThreadController : PBXGDB_Controller
{
    int _processID;
    PBXGDB_MIStoppedState *_lastStoppedState;
    int _lastStopReason;
    BOOL _didSetSchedulerLockingMode;
    BOOL _ignoreNextStop;
}

@property BOOL ignoreNextStop; // @synthesize ignoreNextStop=_ignoreNextStop;
- (void)_updateReasonStoppedMessageForLastStoppedThread;
- (void)_enqueueSchedulerLockingOffSequence;
- (void)_setHitCountForBreakpoint:(id)arg1 withHitCount:(long long)arg2;
- (void)enqueueAttachWaitForSequenceForProcessName:(id)arg1;
- (void)enqueueAttachSequenceForProcessID:(int)arg1;
- (void)enqueueGetSharedLibraryInfoSequenceDoContinue:(BOOL)arg1;
- (void)enqueueSetupSharedLibrarySequence;
- (void)enqueueContinueAfterQuietStopSequence;
- (void)enqueueSuspendSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueResumeSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueContinueSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueRunSequence;
- (void)enqueueStepUntilSequenceForThreadHandle:(unsigned long long)arg1 lineNumber:(unsigned long long)arg2;
- (void)enqueueStepOverSuspendOtherThreadsSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueStepInSuspendOtherThreadsSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueStepOutSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueStepIntoSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueNextInstructionSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueStepInstructionSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueStepOverSequenceForThreadHandle:(unsigned long long)arg1;
- (void)_enqueueStepSequence:(int)arg1 forThreadHandle:(unsigned long long)arg2;
- (void)enqueRequestStackFramesForThread:(unsigned long long)arg1 numberOfStackFrames:(unsigned long long)arg2 resultHandler:(id)arg3;
- (void)enqueueUpdateStackSequenceForThreadHandle:(unsigned long long)arg1;
- (void)enqueueThreadListSequenceWithCurrentThreadID:(long long)arg1 threadState:(int)arg2 suspendedStatus:(long long)arg3;
- (void)_initSequence:(id)arg1 threadHandle:(unsigned long long)arg2;
- (void)setAllThreadsStateToRunning;
- (void)setAllThreadsStateToStepping;
- (void)processStarted;
- (void)_setProcessIsRunning;
- (BOOL)_performBreakpointActionIfPossible:(id)arg1 breakpoint:(id)arg2 context:(id)arg3;
- (void)performActionsForBreakpoint:(id)arg1 startingAtAction:(id)arg2;
- (void)_performActionsForBreakpoint:(id)arg1;
- (void)gdbTargetStopped;
- (void)handleSharedLibraryEventAndContinue:(BOOL)arg1;
- (void)updateThreadsToState:(int)arg1 status:(int)arg2 currentThreadId:(long long)arg3 currentThreadStatus:(long long)arg4 newThreadList:(id)arg5;
- (int)processID;
- (void)setProcessID:(int)arg1;
- (void)setGDBAdaptor:(id)arg1;
- (void)dealloc;

@end

