/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_MIFileListParentCommand.h>

@interface PBXGDB_MIFileListStaticsCommand : PBXGDB_MIFileListParentCommand
{
}

+ (id)miCommandForFile:(id)arg1 shlib:(id)arg2 format:(id)arg3 filter:(id)arg4;
- (void)didFinishWithResultList:(id)arg1;
- (id)GDBCommandString;

@end

