/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_ControlSequence.h>

@interface PBXGDB_RunControlSequence : PBXGDB_ControlSequence
{
    BOOL _isRunning;
}

- (BOOL)handleErrorForMICommand:(id)arg1;
- (void)didFinish:(id)arg1;
- (void)_resultProcessStarted:(id)arg1;
- (void)execute;

@end

