/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXGDB_StringFetchResult.h>

@interface PBXGDB_CStringFetchResult : PBXGDB_StringFetchResult
{
}

- (void)processStringData;
- (void)makeASCIIRepresentationOfBytes:(const char *)arg1 stopAtNull:(BOOL)arg2 stopAtLength:(long long)arg3 resultString:(id)arg4;

@end

