/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DebuggerGDB/PBXLSModel.h>

@class DBGCodeModule, DBGGDBStackFrame, NSMutableArray, NSString, PBXDisassemblyFileDocument, PBXLSDataValue;

@interface PBXLSStackFrame : PBXLSModel
{
    DBGGDBStackFrame *_foundationStackFrame;
    DBGCodeModule *_foundationModule;
    unsigned long long _ipAddress;
    unsigned long long _fpAddress;
    long long _ipLineNumber;
    NSString *_ipFileName;
    NSString *_functionName;
    PBXLSDataValue *_containerDV;
    NSMutableArray *_visibleDataValues;
    struct _NSRange _visibleDataValuesRange;
    PBXDisassemblyFileDocument *_disassemblyDocument;
    unsigned long long _fpIdentifier_lite;
    BOOL _hasSymbols;
    id <DVTObservingToken> _dataValuesObserversObservingToken;
}

+ (unsigned long long)uninitializedFramePointer;
+ (id)uninitializedStackFrame;
+ (id)globalStackFrame;
@property BOOL hasSymbols; // @synthesize hasSymbols=_hasSymbols;
@property(retain) PBXDisassemblyFileDocument *disassemblyDocument; // @synthesize disassemblyDocument=_disassemblyDocument;
@property(retain) DBGCodeModule *foundationModule; // @synthesize foundationModule=_foundationModule;
@property(retain, nonatomic) DBGGDBStackFrame *foundationStackFrame; // @synthesize foundationStackFrame=_foundationStackFrame;
- (void)requestDisassembly:(id)arg1;
- (id)frameNameWithPrefix:(id)arg1;
- (id)mixedFrameName;
- (id)disassemblyFrameName;
- (id)visibleDataItemsVisibleRange:(struct _NSRange *)arg1;
- (void)setVisibleDataItems:(id)arg1 visibleRange:(struct _NSRange *)arg2;
- (void)invalidateDataValues;
- (void)ensureValidDataValues;
- (id)containerDataValue;
- (void)invalidateContainerDataValue;
- (void)threadDidUpdate;
- (void)_shouldUpdateDataValues:(id)arg1;
- (id)displayStackFrameInfo;
- (id)displayFunctionName;
- (id)functionName;
- (void)setFunctionName:(id)arg1;
- (id)realFileName;
- (id)fileName;
- (void)setFileName:(id)arg1;
- (long long)lineNumber;
- (void)setLineNumber:(long long)arg1;
- (unsigned long long)framePointerAddress;
- (void)setFramePointerAddress:(unsigned long long)arg1;
- (unsigned long long)liteFramePointerIdentifer;
- (void)setLiteFramePointerIdentifer:(unsigned long long)arg1;
- (id)instructionPointerAddressString;
- (unsigned long long)instructionPointerAddress;
- (void)setInstructionPointerAddress:(unsigned long long)arg1;
- (id)parentThread;
- (void)dealloc;
@property(readonly, getter=isUninitialized) BOOL uninitialized;
- (id)initWithDebugger:(id)arg1;

@end

