# makefile generated by mcp2make 1.0.2



OBJS =
SUBOBJS =

all: MoreFiles
	@if exist * echo Build completed

rebuild: clean all

clean:
	if exist *.o del *.o
	if exist * del *

MoreFiles: $(SUBOBJS) $(OBJS)

