/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (opts.c)
 *  
 *  It has been AutoGen-ed  January  9, 2014 at 02:54:45 PM by AutoGen 5.15
 *  From the definitions    ./opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 36:3:11 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the getdefs author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The getdefs program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 1999-2012 Bruce Korb, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  getdefs is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  getdefs is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#define OPTION_CODE_COMPILE 1
#include "opts.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (getdefs_opt_strs+0)
#define zLicenseDescrip (getdefs_opt_strs+272)

extern tUsageProc optionUsage;

#ifndef NULL
#  define NULL 0
#endif

/*
 *  getdefs option static const strings
 */
static char const getdefs_opt_strs[2504] =
/*     0 */ "getdefs (GNU AutoGen) 1.5\n"
            "Copyright (C) 1999-2012 Bruce Korb, all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   272 */ "getdefs is free software: you can redistribute it and/or modify it under\n"
            "the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "getdefs is distributed in the hope that it will be useful, but WITHOUT ANY\n"
            "WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS\n"
            "FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more\n"
            "details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   875 */ "Regexp to look for after the \"/*=\"\0"
/*   910 */ "DEFS_TO_GET\0"
/*   922 */ "defs-to-get\0"
/*   934 */ "Alphabetize or use named file\0"
/*   964 */ "ORDERING\0"
/*   973 */ "no-ordering\0"
/*   985 */ "no\0"
/*   988 */ "The first index to apply to groups\0"
/*  1023 */ "FIRST_INDEX\0"
/*  1035 */ "first-index\0"
/*  1047 */ "Input file to search for defs\0"
/*  1077 */ "INPUT\0"
/*  1083 */ "input\0"
/*  1089 */ "subblock definition names\0"
/*  1115 */ "SUBBLOCK\0"
/*  1124 */ "subblock\0"
/*  1133 */ "attribute with list of values\0"
/*  1163 */ "LISTATTR\0"
/*  1172 */ "listattr\0"
/*  1181 */ "Insert source file names into defs\0"
/*  1216 */ "FILELIST\0"
/*  1225 */ "filelist\0"
/*  1234 */ "Definition insertion options\0"
/*  1263 */ "Global assignments\0"
/*  1282 */ "ASSIGN\0"
/*  1289 */ "assign\0"
/*  1296 */ "Assignments common to all blocks\0"
/*  1329 */ "COMMON_ASSIGN\0"
/*  1343 */ "common-assign\0"
/*  1357 */ "File(s) to copy into definitions\0"
/*  1390 */ "COPY\0"
/*  1395 */ "copy\0"
/*  1400 */ "Insert source file name into each def\0"
/*  1438 */ "SRCFILE\0"
/*  1446 */ "srcfile\0"
/*  1454 */ "Insert source line number into each def\0"
/*  1494 */ "LINENUM\0"
/*  1502 */ "linenum\0"
/*  1510 */ "Definition output disposition options:\0"
/*  1549 */ "Output file to open\0"
/*  1569 */ "OUTPUT\0"
/*  1576 */ "output\0"
/*  1583 */ "Invoke AutoGen with defs\0"
/*  1608 */ "AUTOGEN\0"
/*  1616 */ "no-autogen\0"
/*  1627 */ "Template Name\0"
/*  1641 */ "TEMPLATE\0"
/*  1650 */ "template\0"
/*  1659 */ "AutoGen Argument\0"
/*  1676 */ "AGARG\0"
/*  1682 */ "agarg\0"
/*  1688 */ "Base name for output file(s)\0"
/*  1717 */ "BASE_NAME\0"
/*  1727 */ "base-name\0"
/*  1737 */ "Display extended usage information and exit\0"
/*  1781 */ "help\0"
/*  1786 */ "Extended usage information passed thru pager\0"
/*  1831 */ "more-help\0"
/*  1841 */ "Output version information and exit\0"
/*  1877 */ "version\0"
/*  1885 */ "Save the option state to a config file\0"
/*  1924 */ "save-opts\0"
/*  1934 */ "Load options from a config file\0"
/*  1966 */ "LOAD_OPTS\0"
/*  1976 */ "no-load-opts\0"
/*  1989 */ "GETDEFS\0"
/*  1997 */ "getdefs (GNU AutoGen) - AutoGen Definition Extraction Tool - Ver. 1.5\n"
            "USAGE:  %s [ <option-name>[{=| }<val>] ]...\n\0"
/*  2112 */ "/dev/null\0"
/*  2122 */ ".getdefsrc\0"
/*  2133 */ "autogen-users@lists.sourceforge.net\0"
/*  2169 */ "\n"
            "If no ``input'' argument is provided or is set to simply \"-\", and if\n"
            "``stdin'' is not a ``tty'', then the list of input files will be read from\n"
            "``stdin''.\n\0"
/*  2326 */ "\n"
            "This program extracts AutoGen definitions from a list of source files.\n"
            "Definitions are delimited by ``/*=<entry-type> <entry-name>\\n'' and\n"
            "``=*/\\n''.\n\0"
/*  2478 */ "getdefs (GNU AutoGen) 1.5";

/*
 *  defs_to_get option description:
 */
#define DEFS_TO_GET_DESC      (getdefs_opt_strs+875)
#define DEFS_TO_GET_NAME      (getdefs_opt_strs+910)
#define DEFS_TO_GET_name      (getdefs_opt_strs+922)
#define DEFS_TO_GET_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  ordering option description:
 */
#define ORDERING_DESC      (getdefs_opt_strs+934)
#define ORDERING_NAME      (getdefs_opt_strs+964)
#define NOT_ORDERING_name  (getdefs_opt_strs+973)
#define NOT_ORDERING_PFX   (getdefs_opt_strs+985)
#define ORDERING_name      (NOT_ORDERING_name + 3)
#define ORDERING_FLAGS     (OPTST_INITENABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  first_index option description:
 */
#define FIRST_INDEX_DESC      (getdefs_opt_strs+988)
#define FIRST_INDEX_NAME      (getdefs_opt_strs+1023)
#define FIRST_INDEX_name      (getdefs_opt_strs+1035)
#define FIRST_INDEX_DFT_ARG   ((char const*)0)
#define FIRST_INDEX_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  input option description:
 */
#define INPUT_DESC      (getdefs_opt_strs+1047)
#define INPUT_NAME      (getdefs_opt_strs+1077)
#define INPUT_name      (getdefs_opt_strs+1083)
#define INPUT_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  subblock option description:
 */
#define SUBBLOCK_DESC      (getdefs_opt_strs+1089)
#define SUBBLOCK_NAME      (getdefs_opt_strs+1115)
#define SUBBLOCK_name      (getdefs_opt_strs+1124)
#define SUBBLOCK_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  listattr option description:
 */
#define LISTATTR_DESC      (getdefs_opt_strs+1133)
#define LISTATTR_NAME      (getdefs_opt_strs+1163)
#define LISTATTR_name      (getdefs_opt_strs+1172)
#define LISTATTR_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  filelist option description:
 */
#define FILELIST_DESC      (getdefs_opt_strs+1181)
#define FILELIST_NAME      (getdefs_opt_strs+1216)
#define FILELIST_name      (getdefs_opt_strs+1225)
#define FILELIST_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  doc_insert option description:
 */
#define DOC_INSERT_DESC      (getdefs_opt_strs+1234)
#define DOC_INSERT_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  assign option description:
 */
#define ASSIGN_DESC      (getdefs_opt_strs+1263)
#define ASSIGN_NAME      (getdefs_opt_strs+1282)
#define ASSIGN_name      (getdefs_opt_strs+1289)
#define ASSIGN_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  common_assign option description:
 */
#define COMMON_ASSIGN_DESC      (getdefs_opt_strs+1296)
#define COMMON_ASSIGN_NAME      (getdefs_opt_strs+1329)
#define COMMON_ASSIGN_name      (getdefs_opt_strs+1343)
#define COMMON_ASSIGN_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  copy option description:
 */
#define COPY_DESC      (getdefs_opt_strs+1357)
#define COPY_NAME      (getdefs_opt_strs+1390)
#define COPY_name      (getdefs_opt_strs+1395)
#define COPY_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  srcfile option description:
 */
#define SRCFILE_DESC      (getdefs_opt_strs+1400)
#define SRCFILE_NAME      (getdefs_opt_strs+1438)
#define SRCFILE_name      (getdefs_opt_strs+1446)
#define SRCFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  linenum option description:
 */
#define LINENUM_DESC      (getdefs_opt_strs+1454)
#define LINENUM_NAME      (getdefs_opt_strs+1494)
#define LINENUM_name      (getdefs_opt_strs+1502)
#define LINENUM_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  doc_output option description:
 */
#define DOC_OUTPUT_DESC      (getdefs_opt_strs+1510)
#define DOC_OUTPUT_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  output option description:
 */
#define OUTPUT_DESC      (getdefs_opt_strs+1549)
#define OUTPUT_NAME      (getdefs_opt_strs+1569)
#define OUTPUT_name      (getdefs_opt_strs+1576)
#define OUTPUT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  autogen option description:
 */
#define AUTOGEN_DESC      (getdefs_opt_strs+1583)
#define AUTOGEN_NAME      (getdefs_opt_strs+1608)
#define NOT_AUTOGEN_name  (getdefs_opt_strs+1616)
#define NOT_AUTOGEN_PFX   (getdefs_opt_strs+985)
#define AUTOGEN_name      (NOT_AUTOGEN_name + 3)
#define AUTOGEN_FLAGS     (OPTST_INITENABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  template option description:
 */
#define TEMPLATE_DESC      (getdefs_opt_strs+1627)
#define TEMPLATE_NAME      (getdefs_opt_strs+1641)
#define TEMPLATE_name      (getdefs_opt_strs+1650)
#define TEMPLATE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  agarg option description with
 *  "Must also have options" and "Incompatible options":
 */
#define AGARG_DESC      (getdefs_opt_strs+1659)
#define AGARG_NAME      (getdefs_opt_strs+1676)
#define AGARG_name      (getdefs_opt_strs+1682)
static int const aAgargCantList[] = {
    INDEX_OPT_OUTPUT, NO_EQUIVALENT };
#define AGARG_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  base_name option description with
 *  "Must also have options" and "Incompatible options":
 */
#define BASE_NAME_DESC      (getdefs_opt_strs+1688)
#define BASE_NAME_NAME      (getdefs_opt_strs+1717)
#define BASE_NAME_name      (getdefs_opt_strs+1727)
static int const aBase_NameCantList[] = {
    INDEX_OPT_OUTPUT, NO_EQUIVALENT };
#define BASE_NAME_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (getdefs_opt_strs+1737)
#define HELP_name       (getdefs_opt_strs+1781)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (getdefs_opt_strs+1786)
#define MORE_HELP_name  (getdefs_opt_strs+1831)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (getdefs_opt_strs+1841)
#define VER_name        (getdefs_opt_strs+1877)
#define SAVE_OPTS_DESC  (getdefs_opt_strs+1885)
#define SAVE_OPTS_name  (getdefs_opt_strs+1924)
#define LOAD_OPTS_DESC     (getdefs_opt_strs+1934)
#define LOAD_OPTS_NAME     (getdefs_opt_strs+1966)
#define NO_LOAD_OPTS_name  (getdefs_opt_strs+1976)
#define LOAD_OPTS_pfx      (getdefs_opt_strs+985)
#define LOAD_OPTS_name     (NO_LOAD_OPTS_name + 3)
/*
 *  Declare option callback procedures
 */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Getdefs Option Descriptions.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_DEFS_TO_GET,
     /* equiv idx, value */ 0, VALUE_OPT_DEFS_TO_GET,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEFS_TO_GET_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --defs_to_get */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DEFS_TO_GET_DESC, DEFS_TO_GET_NAME, DEFS_TO_GET_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_ORDERING,
     /* equiv idx, value */ 1, VALUE_OPT_ORDERING,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ORDERING_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --ordering */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ORDERING_DESC, ORDERING_NAME, ORDERING_name,
     /* disablement strs */ NOT_ORDERING_name, NOT_ORDERING_PFX },

  {  /* entry idx, value */ 2, VALUE_OPT_FIRST_INDEX,
     /* equiv idx, value */ 2, VALUE_OPT_FIRST_INDEX,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FIRST_INDEX_FLAGS, 0,
     /* last opt argumnt */ { FIRST_INDEX_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ FIRST_INDEX_DESC, FIRST_INDEX_NAME, FIRST_INDEX_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_INPUT,
     /* equiv idx, value */ 3, VALUE_OPT_INPUT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ INPUT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --input */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ INPUT_DESC, INPUT_NAME, INPUT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_SUBBLOCK,
     /* equiv idx, value */ 4, VALUE_OPT_SUBBLOCK,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ SUBBLOCK_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --subblock */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ SUBBLOCK_DESC, SUBBLOCK_NAME, SUBBLOCK_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_LISTATTR,
     /* equiv idx, value */ 5, VALUE_OPT_LISTATTR,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ LISTATTR_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --listattr */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ LISTATTR_DESC, LISTATTR_NAME, LISTATTR_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_FILELIST,
     /* equiv idx, value */ 6, VALUE_OPT_FILELIST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FILELIST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --filelist */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FILELIST_DESC, FILELIST_NAME, FILELIST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_INSERT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DOC_INSERT_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_ASSIGN,
     /* equiv idx, value */ 8, VALUE_OPT_ASSIGN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ ASSIGN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --assign */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ ASSIGN_DESC, ASSIGN_NAME, ASSIGN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_COMMON_ASSIGN,
     /* equiv idx, value */ 9, VALUE_OPT_COMMON_ASSIGN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ COMMON_ASSIGN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --common_assign */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ COMMON_ASSIGN_DESC, COMMON_ASSIGN_NAME, COMMON_ASSIGN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 10, VALUE_OPT_COPY,
     /* equiv idx, value */ 10, VALUE_OPT_COPY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ COPY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --copy */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ COPY_DESC, COPY_NAME, COPY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_SRCFILE,
     /* equiv idx, value */ 11, VALUE_OPT_SRCFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SRCFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --srcfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SRCFILE_DESC, SRCFILE_NAME, SRCFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_LINENUM,
     /* equiv idx, value */ 12, VALUE_OPT_LINENUM,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LINENUM_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --linenum */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LINENUM_DESC, LINENUM_NAME, LINENUM_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_OUTPUT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DOC_OUTPUT_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_OUTPUT,
     /* equiv idx, value */ NOLIMIT, NOLIMIT,
     /* equivalenced to  */ INDEX_OPT_AUTOGEN,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OUTPUT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --output */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ OUTPUT_DESC, OUTPUT_NAME, OUTPUT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_AUTOGEN,
     /* equiv idx, value */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ AUTOGEN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --autogen */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ AUTOGEN_DESC, AUTOGEN_NAME, AUTOGEN_name,
     /* disablement strs */ NOT_AUTOGEN_name, NOT_AUTOGEN_PFX },

  {  /* entry idx, value */ 16, VALUE_OPT_TEMPLATE,
     /* equiv idx, value */ 16, VALUE_OPT_TEMPLATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TEMPLATE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --template */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TEMPLATE_DESC, TEMPLATE_NAME, TEMPLATE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_AGARG,
     /* equiv idx, value */ 17, VALUE_OPT_AGARG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ AGARG_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --agarg */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aAgargCantList,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ AGARG_DESC, AGARG_NAME, AGARG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_BASE_NAME,
     /* equiv idx, value */ 18, VALUE_OPT_BASE_NAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BASE_NAME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --base_name */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aBase_NameCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ BASE_NAME_DESC, BASE_NAME_NAME, BASE_NAME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_SAVE_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SAVE_OPTS_DESC, NULL, SAVE_OPTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_LOAD_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ LOAD_OPTS_DESC, LOAD_OPTS_NAME, LOAD_OPTS_name,
     /* disablement strs */ NO_LOAD_OPTS_name, LOAD_OPTS_pfx }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Getdefs Option Environment
 */
#define zPROGNAME       (getdefs_opt_strs+1989)
#define zUsageTitle     (getdefs_opt_strs+1997)
#define zRcName         (getdefs_opt_strs+2122)
static char const * const apzHomeList[2] = {
    getdefs_opt_strs+2112,
    NULL };
#define zBugsAddr       (getdefs_opt_strs+2133)
#define zExplain        (getdefs_opt_strs+2169)
#define zDetail         (getdefs_opt_strs+2326)
#define zFullVersion    (getdefs_opt_strs+2478)
/* extracted from optcode.tlib near line 349 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define getdefs_full_usage (NULL)

#define getdefs_short_usage (NULL)

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the USAGE() macro.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    (void)pOptions;
    USAGE(GETDEFS_EXIT_SUCCESS);
}
/* extracted from optmain.tlib near line 1093 */

#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

#ifndef  WITH_PACKAGER
# define getdefs_packager_info NULL
#else
static char const getdefs_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport getdefs bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif

tOptions getdefsOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NEGATIONS
    + OPTPROC_NO_ARGS ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      3 /* index of default opt */
    },
    24 /* full option count */, 19 /* user option count */,
    getdefs_full_usage, getdefs_short_usage,
    NULL, NULL,
    PKGDATADIR, getdefs_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

static char*
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(GETDEFS_EXIT_FAILURE);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/*
 *  This invokes the translation code (e.g. gettext(3)).
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &getdefsOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        getdefsOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* opts.c ends here */
